= Release notes v.5.8

== Table of Contents

* Log Request ID and Internal Request ID via SLF4J MDC

== Log Request ID and Internal Request ID via SLF4J MDC

From now on, InR-ID and X-Request-ID values are provided to the logs via SLF4J's Mapped Diagnostic Context (MDC).
These values are no longer provided explicitly in XS2A log messages, but they can be retrieved by the logging framework from MDC.
This change also affects `access-log` and `request-log`, meaning that log messages in these loggers no longer contain InR-ID and X-Request-ID.

Default log configuration file for Logback in XS2A has been changed to include these IDs.
In case of using custom logging configuration, SPI developer should adjust existing configuration to get and display stored IDs from MDC.
Internal Request ID(logged as InR-ID) and X-Request-ID are stored in the MDC under `internal-request-id` and `x-request-id` keys.

These IDs are also propagated from XS2A to CMS and ASPSP profile services via `X-Request-ID` and `X-Internal-Request-ID` headers and can be retrieved from MDC using already mentioned keys.
