= Release notes v.7.8

== Table of Contents

* Implement explicit authorisation for PIIS consents
* Implement multilevel for PIIS consents
* Incorrect consent type in PIIS Consent
* Adjust CoF request with consent created by TPP

== Implement explicit authorisation for PIIS consents

From now on, explicit authorisation for PIIS consent is supported in Redirect and Embedded approach.
To configure redirect url for PIIS consent use `piisRedirectUrlToAspsp` parameter in `redirectLinkToOnlineBanking` block in ASPSP Profile.

== Implement multilevel SCA for PIIS consents

For account with multiple PSUs, now it is possible to execute multilevel SCA for each PSU.
Piis Consent response from spi `SpiInitiatePiisConsentResponse` contains boolean field `multilevelScaRequired` to inform XS2A
that this PIIS Consent requires multilevel SCA and there should be always explicit authorisation approach used.

== Incorrect consent type in PIIS Consent

From now on, PIIS Consent type can have any of following values either `PIIS_ASPSP` or `PIIS_TPP`.

== Adjust CoF request with consent created by TPP

From now on, TPP is able to make Confirmation of Funds request `POST /v1/funds-confirmations` with TPP consent by providing id of the consent in `Consent-Id` header.
In this case Confirmation of Funds Consent will be retrieved from CMS and will be passed to the SPI level.
