= Release notes v.9.0

== Table of Contents

* Removed deprecated authorisation type AIS
* Refactored profile
* Added migration file for creation signing basket table
* Fixed internal server error on `GET aspsp-api/v1/ais/consents/account/{account-id}` with oracle db
* Fixed deadlock while saving authentication methods for authorisation
* Added field charge bearer

== Removed deprecated authorisation type AIS

From now on, deprecated authorisation type AIS removed, use authorisation type CONSENT instead.

== Refactored profile

From now on, signing basket profile properties `signingBasketSupported`, `signingBasketMaxEntries`,
`notConfirmedSigningBasketExpirationTimeMs` located in separate field of `SbAspspProfileSetting` inside
`AspspSettings`.

== Added migration file for creation signing basket table

From now on, signing basket table added into cms database along with all required related tables for
storing signing basket. Also, added columns `signing_basket_blocked` into `consents` and `pis_common_payment
tables.

== Fixed internal server error on `GET aspsp-api/v1/ais/consents/account/{account-id}` with oracle db

From now on, endpoint `GET aspsp-api/v1/ais/consents/account/{account-id}` works correct with oracle db

== Fixed deadlock while saving authentication methods for authorisation

From now on, authentication methods for authorisation saving only in case they differ from already
saved one for same authorisation.

== Added field charge bearer

Added field charge bearer to `PaymentInitiationJson`, `PaymentInitiationWithStatusResponse`, `PaymentInitiationBulkElementJson`
and passed this field to spi level. From now on, `SpiSinglePayment` contains String field `chargeBearer`.
For validating this field according to bank requirements, extend payment validation on connector side.
Instruction how to do that one can find in `Extending payment validation.adoc`.
