= Release notes v.5.1

== Table of Contents
* Change yaml-generator to correct model Objects equals
* SCA exemption is supported
* Bugfix: Wrong PSU-ID can authorise endpoints
* Bugfix: Don't provide `creditorAddress` field in get payment response if it was absent in initiate payment request

== Change yaml-generator to correct model Objects equals

From now on, instances of generated models in `xs2a-server-api` module will correctly compare superclass properties in `equals` method.

== SCA exemption is supported

From now on, SCA exemption is possible for bulk and single payment initiation. To support this, return type of
`AuthorisationSpi#authorisePsu` method was changed from `SpiAuthorisationStatus` to `SpiPsuAuthorisationResponse`.
`SpiPsuAuthorisationResponse` is a new domain class, which contains authorisation status as well as boolean `scaExempted`
field, which is taken into account by XS2A for performing SCA exemption. If the psu authorisation spi response for
bulk or single will be successful and `scaExempted` is `true` - SCA will not be performed, 'PaymentSpi#executePaymentWithoutSca'
will be invoked and authorisation status will be set to `EXEMPTED`. SCA exemption is supported for multilevel SCA too.

== Wrong PSU-ID can authorise endpoints

From now on, PSU that is different from the PSU in authorisation can not update data on the authorisation resource.
This applies to the following endpoints:

* consent `PUT /v1/consents/{consentId}/authorisations/{authorisationId}`,
* payment `PUT /v1/{payment-service}/{payment-product}/{payment-id}/authorisations/{authorisation-id}`,
* payment cancellation `PUT /v1/{payment-service}/{payment-product}/{payment-id}/cancellation-authorisations/{cancellation-id}`.

== Bugfix: Don't provide `creditorAddress` field in get payment response if it was absent in initiate payment request

From now on, `creditorAddress` field is absent in get payment response `GET /v1/{payment-service}/{payment-product}/{paymentId}`
if it was not provided in initiate payment request `POST /v1/{payment-service}/{payment-product}`
