== Table of Contents

* Fixed wrong password sca handling
* Increased length limit of TPP-URIs to Max500Text
* Added Postman tests for `cms-psu-api` controllers
* Provided interfaces for CMS web controllers in `consent-aspsp-web`, `consent-psu-web` and `consent-xs2a-web`
* Created script to delete deprecated type of access `OWNER_ADDRESS` in `account_access` and `aspsp_account_access` tables

== Fixed wrong password sca handling

From now on, it's possible to enter password and tan as many times, as bank allows you to.

== Increased length limit of TPP-URIs to Max500Text

From now on, maximum allowed lengths for `tpp-redirect-uri` and `tpp-nok-redirect-uri` is 500 symbols.

== Added Postman tests for `cms-psu-api` controllers

Added Postman tests for `cms-psu-api` controllers: `AspspConsentDataPsuApiController`, `CmsPsuAisController`, `CmsPsuPiisController`, `CmsPsuPisController`.

== Provided interfaces for CMS web controllers in `consent-aspsp-web`, `consent-psu-web` and `consent-xs2a-web`

Provided interfaces for CMS web controllers in `consent-aspsp-web`, `consent-psu-web` and `consent-xs2a-web`.

== Created script to delete deprecated type of access `OWNER_ADDRESS` in `account_access` and `aspsp_account_access` tables

Created script to delete deprecated type of access `OWNER_ADDRESS` in `account_access` and `aspsp_account_access` tables.
