= Release notes v.7.7

== Table of Contents

* Add authorisation endpoints to CoF yaml
* Implement implicit authorisation for PIIS consents
* Add update PSU for confirmation of funds consent to CMS-PSU-API
* Add get authorisation of confirmation of funds to CMS-PSU-API

== Add authorisation endpoints to CoF yaml

Authorisation endpoints were added to Confirmation of Funds yaml and the following methods were generated in `ConfirmationOfFundsController`:

- Start the authorisation process for a consent `POST /v2/consents/confirmation-of-funds/{consentId}/authorisations`

- Get consent authorisation sub-resources request `GET /v2/consents/confirmation-of-funds/{consentId}/authorisations`

- Read the SCA status of the consent authorisation `GET /v2/consents/confirmation-of-funds/{consentId}/authorisations/{authorisationId}`

- Update PSU Data for consents `PUT /v2/consents/confirmation-of-funds/{consentId}/authorisations/{authorisationId}`

== Implement implicit authorisation for PIIS consents

From now on, implicit authorisation for PIIS consent is supported in Redirect and Embedded approach.
To configure redirect url for PIIS consent use `piisRedirectUrlToAspsp` parameter in `redirectLinkToOnlineBanking` block in ASPSP Profile.

== Add update PSU in confirmation of funds consent to CMS-PSU-API

Added resource to update PSU for confirmation of funds (PIIS v2) to `CMS-PSU_API`:

```
PUT psu-api/v2/piis/consent/{consent-id}/authorisation/{authorisation-id}/psu-data
```

== Add get authorisation of confirmation of funds to CMS-PSU-API

Added resource to get authorisation of confirmation of funds (PIIS v2) to `CMS-PSU_API`:

```
GET psu-api/v2/piis/consent/authorisation/{authorisation-id}
```
