= Release notes v.10.6

== Table of Contents

* Fixed cancellation flow
* Fixed NPE for get transactions list without get account list
* Changed transactionDetails structure
* Removed withBalance field from read card transactions list
* Bumped hibernate-validator from 6.1.0.Final to 6.1.5.Final
* Bumped snakeyaml from 1.23 to 1.26

== Fixed cancellation flow

From now on, update Payment Cancellation Tpp Redirect Uri and update Payment Cancellation Internal Request Id will
be performed only for successful cancellation responses.

== Fixed NPE for get transactions list without get account list

From now on, for get transaction list request with incorrect account id, the response will be `400 FORMAT_ERROR_UNKNOWN_ACCOUNT`.

== Changed transactionDetails structure

From now on, `transactionDetails` are stored in `Transactions` object, and response has correct structure. Before they were stored in `transactionDetailsBody` object, and this was the cause of the incorrect structure of the response. Unnecessary `TransactionDetailsBody` object model was removed.

== Removed withBalance field from read card transactions list

From now on withBalance field is removed from read card transactions list, since it is not required under implementation guidelines version 1.3.8.

== Bumped hibernate-validator from 6.1.0.Final to 6.1.5.Final

From now on hibernate-validator is updated to version 6.1.5.Final

== Bumped snakeyaml from 1.23 to 1.26

From now on snakeyaml is updated to version 1.26
