= Release notes v.2.10

== Table of Contents
* Include TPP roles in all access-log for all request entries
* Bugfix: Finalised status of AIS consent changes after expiration
* Bugfix: Payment and Consent initiation request where field X-Request-ID contains an invalid UUID return internal server error
* Bugfix: Fix `scaRedirect` link in payment cancellation in case of implicit authorisation
* Include Redirect-ID in all access-log for the responses where applicable
* Log HTTP requests and responses to a separate logger
* Bugfix: Fix get common payment by redirect-id
* Bugfix: Optional fields in JSON structure are commented in yaml
* New internal request id

== Include TPP roles in all access-log for all request entries
From now on, request entries in access-log will also contain list of TPP roles, extracted from the certificate.

== Bugfix: Payment and Consent initiation request where field X-Request-ID contains an invalid UUID return internal server error

From now on, while initiate payment or consent with invalid field `X-Request-ID` we'll see `400 FROMAT_ERROR` response with validator message instead
`500 Internal Server Error`

== Bugfix: Finalised status of AIS consent changes after expiration

From now on, no changes can be done to the status of consent when it is expired or finalised
while getting AIS Consent (`GET /psu-api/v1/ais/consent/{consent-id}` or `GET /api/v1/ais/consent/{consent-id}`) in CMS.

== Bugfix: Fix `scaRedirect` link in payment cancellation in case of implicit authorisation
From now on, `scaRedirect` link in response to payment cancellation request (`DELETE /v1/{payment-service}/{payment-product}/{paymentId}`)
in Redirect approach in case of implicit authorisation will be correctly generated based on the `pisPaymentCancellationRedirectUrlToAspsp`
property in the ASPSP profile instead of the `pisRedirectUrlToAspsp` one.

== Include Redirect-ID in all access-log for the responses where applicable
From now on, response entries in access-log will also contain redirect ID, if it's present in the response.

== Log HTTP requests and responses to a separate logger
From now, all HTTP requests and responses are being logged to a separate logger (`request-log`).
At the moment this logger records:

 - request URI with query params
 - request headers
 - request payload
 - response status
 - response headers
 - response body

Logging can be configured in the `logback-spring.xml` file. By default, log records from this logger are being written to the console only.
This behaviour can be changed by configuring the `logback-spring.xml`.

== Bugfix: Fix get common payment by redirect-id

Executing GET pain common payment in CMS-PSU-API on `/psu-api/v1/payment/redirect/{redirect-id}` or `/psu-api/v1/payment/cancellation/redirect/{redirect-id}`
caused internal server error. From now on, this bug is fixed.

== Bugfix: Optional fields in JSON structure are commented in yaml
From now on, TPP can provide `ultimateDebtor`, `ultimateCreditor`, `purposeCode`, `remittanceInformationStructured` fields
in request body during payment initiation process (`POST /v1/{payment-service}/{payment-product}`). These fields
are available in payment objects in SPI API. Added validators for these fields.
Also these fields present in `CmsPayment` object in CMS-PSU-API and CMS-ASPSP-API.

== New internal request ID
From now on, XS2A generates internal request ID (`InR-Id`) for each incoming request from TPP in order to uniquely identify requests.
Unlike the `X-Request-ID`, which is generated and provided by the TPP, `InR-Id` is guaranteed to be unique.
This internal request ID is now provided to the SPI inside the `de.adorsys.psd2.xs2a.spi.domain.SpiContextData`.
It was also added to the events and `access-log`.
