= Release notes v.10.10

== Table of Contents

* Refactored scheduler for Non-recurring consent expiration task, fixed flow for NotConfirmedConsentExpirationScheduleTask

* Fixed bug for Read Transaction List with bookingStatus=INFORMATION parameter

* Refactored logging mechanism in BaseAuthorisationProcessorService class

== Refactored scheduler for Non-recurring consent expiration task, fixed flow for NotConfirmedConsentExpirationScheduleTask

Schedulers for Non-recurring consent expiration task and Not Confirmed Consent Expiration task are recommended to be run separately with at least 15 min interval to avoid of database inner locks. Fixed bug in NotConfirmedConsentExpirationScheduleTask flow, as a result all not confirmed consents are now expiring according to ASPSP profile settings.

== Fixed bug for Read Transaction List with bookingStatus=INFORMATION parameter

From now on, reading Transaction List with query parameter bookingStatus=INFORMATION returns successful response even with the absence of other query parameters.

== Refactored logging mechanism in BaseAuthorisationProcessorService class

Logging mechanism was refactored in this class and all the inherited ones.
