= Release notes v.5.2

== Table of Contents

* Add integration test for embedded mode for XS2A
* Bugfix: the field `lastActionDate` was not updated in piis_consent DB table
* Remove redundant request to delete ASPSP consent data on consent creation
* Create Bulk Payment validators

== Add integration test for embedded mode for XS2A

Integration test has been added for XS2A to ensure that application correctly starts with embedded CMS and ASPSP Profile.

== Bugfix: the field `lastActionDate` was not updated in piis_consent DB table

From now on, initial value is set to the field `lastActionDate` in case of PIIS consent creation.
Also, new value is set if the consent was revoked.

== Remove redundant request to delete ASPSP consent data on consent creation

From now on, XS2A won't try to delete ASPSP consent data in CMS for newly created AIS consent before the consent was passed to SPI.

== Create Bulk Payment validators

From now on all fields of bulk payments are validated according to specification.
