= Release notes v.2.7

== Table of Contents
* Bugfix: Consent-related endpoints return incorrect HTTP status code on providing unknown consent ID
* Bugfix: Validate `entryReferenceFrom` and `deltaList` parameters in `Read Transaction List` request
* Bugfix: Сreate consent request and update PSU authorisation request returns empty list of scaMethods in response
* Bugfix: `Get Consent` request doesn't return mandated `lastActionDate` attribute in response body

== Bugfix: Consent-related endpoints return incorrect HTTP status code on providing unknown consent ID
From now on, AIS endpoints that take consent ID as a path parameter will return `CONSENT_UNKNOWN` error with HTTP status
 code `403` instead of `400` if the consent couldn't be located by the provided ID.

The following endpoints were affected by this change:

- Get Status Request (`GET /v1/consents/{consentId}/status`)
- Delete an Account Information Consent Object (`DELETE /v1/consents/{consentId}`)
- Start the authorisation process in context of an Account Information Consent Request (`POST /v1/consents/{consentId}/authorisations`)
- Update PSU Data in context of an Account Information Consent Request (`PUT /v1/consents/{consentId}/authorisations/{authorisationId}`)
- Get Authorisation Sub-Resources Request in context of an Account Information Consent Request (`GET /v1/consents/{consentId}/authorisations`)
- Get SCA Status Request in context of an Account Information Consent Request (`GET /v1/consents/{consentId}/authorisations/{authorisationId}`)

== Bugfix: Validate `entryReferenceFrom` and `deltaList` parameters in `Read Transaction List` request

Parameter `deltaReportSupported` was removed from ASPSP Profile.
From now on, ASPSP Profile has two parameters: `deltaListSupported` and `entryReferenceFromSupported` that indicate the support of corresponding parameters in `Read Transaction List` request `GET /v1/accounts/{account-id}/transactions`.
When TPP sends request and it has either `entryReferenceFrom` or `deltaList` parameter, and ASPSP doesn't support them, then TPP will receive `400 Bad Request` error with `PARAMETER_NOT_SUPPORTED` code.
If ASPSP supports both parameters and TPP sends request with these two parameters, it will also receive `400 Bad Request` error with `FORMAT_ERROR` code.

== Bugfix: Сreate consent request and update PSU authorisation request returns empty list of scaMethods in response

From now on, the responses for these requests don't include empty list of scaMethods in case when no SCA methods
are returned from SPI level:

- POST `/v1/consents`;
- PUT `/v1/consents/{consent_id}/authorisations/{authorisation_id}`.

== Bugfix: Validate `bookingStatus` query parameter in `Read Transaction List` request

From now on, mandatory `bookingStatus` query parameter is being validated in `Read Transaction List` request
(`GET /v1/accounts/{account-id}/transactions {query-parameters}`).
To be considered valid, this parameter should be present in request and have a valid value (`booked`, `pending` or `both`).

== Bugfix: `creditorAddress` property is provided to the SPI in payment object even if it was not present in the request

Parameter `creditorAddress` in `de.adorsys.psd2.xs2a.spi.domain.payment.SpiSinglePayment` and `de.adorsys.psd2.xs2a.spi.domain.payment.SpiPeriodicPayment`
will be to set to null if it is absent in the `initiatePayment` request (`POST /v1/{payment-service}/{payment-product}`)

== Added validation of accept header for getting transaction list (`GET /v1/accounts/{account-id}/transactions`)

Configuration property `supportedTransactionApplicationTypes` was added to bank profile with list of supported headers (JSON, XML, TEXT).

* `Accept` header (if it is presented in request) should be one of application/json, application/xml or text/plain and configured in bank profile.
* If property `supportedTransactionApplicationTypes` is not configured validation will not be applied and header can be one of JSON, XML, TEXT as in specification.
* If header `Accept` is not provided in request - respond with JSON format.

== Bugfix: `Get Consent` request doesn't return mandated `lastActionDate` attribute in response body

Until now, when TPP made first `Get Consent` request, `lastActionDate` field was absent in the response.
From now on, the value of the `lastActionDate` field is set to the current date when AIS Consent is created and will always be present in the `Get Consent` response.
