= Release notes v.8.1

== Table of Contents

* Fixed internal server error on `GET aspsp-api/v1/ais/consents/account/{account-id}` with oracle db
* Fixed deadlock while saving authentication methods for authorisation
* Added field charge bearer

== Fixed internal server error on `GET aspsp-api/v1/ais/consents/account/{account-id}` with oracle db

From now on, endpoint `GET aspsp-api/v1/ais/consents/account/{account-id}` works correct with oracle db

== Fixed deadlock while saving authentication methods for authorisation

From now on, authentication methods for authorisation saving only in case they differ from already
saved one for same authorisation.

== Added field charge bearer

Added field charge bearer to `PaymentInitiationJson`, `PaymentInitiationWithStatusResponse`, `PaymentInitiationBulkElementJson`
and passed this field to spi level. From now on, `SpiSinglePayment` contains String field `chargeBearer`.
For validating this field according to bank requirements, extend payment validation on connector side.
Instruction how to do that one can find in `Extending payment validation.adoc`.
