= Release notes v.5.4

== Table of Contents

* Implement support of Multicurrency Accounts
* Improve payment type validation
* Not possible to work with consent that was created in xs2a v.5.1 and earlier
* Incorrect scaStatus for failed authorisation PIS/AIS/Payments-Cancellation
* Provide creation date and time in SPI Request
* Incorrect consent status for already used one time consent

== Implement support of Multicurrency Accounts

From now on, XS2A supports flows for multicurrency accounts.
A multicurrency account is an account which is a collection of different sub-accounts which are all addressed by the same account identifier like an IBAN by e.g. payment initiating parties.
The sub-accounts are legally different accounts and they all differ in their currency, balances and transactions.
An account identifier like an IBAN together with a currency always addresses uniquely a sub-account of a multicurrency account.
ASPSP can grant data access to multicurrency account on SUBACCOUNT, AGGREGATION or AGGREGATION_AND_SUBACCOUNT level by setting `multicurrencyAccountLevelSupported` property in ASPSP-Profile.

== Improve payment type validation

From now on, all payment and payment cancellation requests are validated to have proper
payment type and payment service.

== Not possible to work with consent that was created in xs2a v.5.1 and earlier

From now on, it is possible to work with consent that was created in xs2a v.5.1 and earlier.

== Incorrect scaStatus for failed authorisation PIS/AIS/Payments-Cancellation

From now on, update PSU data and initiate endpoints for PIS, AIS and Payment-Cancellation return `scaStatus: failed` when
encountering `PSU_CREDENTIALS_INVALID`.

== Provide creation date and time in SPI Request

From now on, consent and payment in SPI level incorporate `creationTimestamp` field that represents information about when object was created.

== Incorrect consent status for already used one time consent

From now on, all one-off consents (`recurringIndicator` = false and `frequencyPerDay` = 1) are being checked for
using all possible combinations of GET endpoints (accounts, balances, transactions). If all possible GET endpoints were
used - the consent receives the `EXPIRED` status.
