= Release notes v.4.2

== Table of Contents

* Add integration test for embedded mode for XS2A
* Bugfix: the field `lastActionDate` was not updated in piis_consent DB table
* Remove TppRedirectUri from TppInfo
* Remove PSU Data from update consent status requests in cms-psu-api

== Add integration test for embedded mode for XS2A

Integration test has been added for XS2A to ensure that application correctly starts with embedded CMS and ASPSP Profile.

== Bugfix: the field `lastActionDate` was not updated in piis_consent DB table

From now on, initial value is set to the field `lastActionDate` in case of PIIS consent creation. Also, new value is
set if the consent was revoked.

== Remove TppRedirectUri from TppInfo

From now on deprecated field `tppRedirectUri` is removed from `TppInfo`. And  fields `redirectUri`, `nokRedirectUri`,
`cancelRedirectUri`, `cancelNokRedirectUri` are removed from `TppInfoEntity`. Columns `redirect_uri`, `nok_redirect_uri`,
`cancel_redirect_uri`, `cancel_nok_redirect_uri` from `tpp_info table` will be removed in v.4.5.

== Remove PSU Data from update consent status requests in cms-psu-api

From now on parameter `PsuIdData` became deprecated in interface `CmsPsuAisService` methods: `confirmConsent`,
`rejectConsent`, `revokeConsent`. Also in `CmsPsuAisController` methods `confirmConsent`, `rejectConsent`,
`revokeConsent` headers `psuId`, `psuIdType`, `psuCorporateId`, `psuCorporateIdType` now are deprecated.
All this deprecated parameters will be removed in version 4.5.
