= Release notes v.5.11

== Table of Contents

* Funds confirmation consents migration
* Change PIIS consent Java classes in SPI and CMS APIs
* Deprecate TPP access type in PIIS consents

== Funds confirmation consents migration

All existing PIIS consents were moved from `piis_consent` database table to `consent` one.
During the migration process the following consents were ignored and won't be usable anymore:

- consents with TPP access type set to `ALL_TPP`
- consents created for TPP that's unknown to XS2A (i. e. with TPP authorisation number that's not present in `tpp_info` table)

== Change PIIS consent Java classes in SPI and CMS APIs

Previously used PIIS consent model `de.adorsys.psd2.xs2a.core.piis.PiisConsent` was replaced with separate models for CMS and SPI with identical content.

All services related to PIIS consents in `consent-aspsp-api` and `consent-psu-api` are now using `de.adorsys.psd2.consent.api.piis.CmsPiisConsent`.
`FundsConfirmationSpi` is now operating with `de.adorsys.psd2.xs2a.spi.domain.piis.SpiPiisConsent`.

== Deprecate TPP access type in PIIS consents

From now on, `tppAccessType` property in PIIS consent models is deprecated and will be removed in the future.
All PIIS consents are considered to be created for single TPP only.
