= Release notes v. 3.8

== Table of Contents
* Refactor: ASPSP consent data refactoring
* Feature: Only authorisation number is used to identify TPP
* Feature: CMS-PSU-API enriching responses
* Refactor: Event API refactoring

== Refactor: ASPSP consent data refactoring

From now on, the data in SPI level communication is changed. Before, we used `AspspConsentData` object to store the byte array of ASPSP consent data and this object was used in all SPI methods signature as a parameter.
After this refactoring, new provider is used instead of this object: `SpiAspspConsentDataProvider`. This provider is transferred from XS2A
to SPI level and can be used for storing (`updateAspspConsentData` method) and loading (`loadAspspConsentData` method) the ASPSP consent data.
So, now the SPI developers should change their connectors according to these changes: replace the `AspspConsentData` parameter with
`SpiAspspConsentDataProvider` parameter in the SPI implementation.
Also, field `aspspConsentData` and method `success()` were removed as deprecated from `SpiResponse` entity. Please use method `build()` instead.

Please note: from now on, the SPI developers are responsible for saving the ASPSP consent data to the database. XS2A-Core provides this possibility, but if no updateAspspConsentData call happens, no data will be saved.

== Feature: Only authorisation number is used to identify TPP

From now on, only authorisation number field in QWAC Certificate is used to identify TPP. Before, national authority id
was used for TPP identification as well. Column `authority_id` in `tpp_stop_list` table was marked as deprecated and will
be removed in version 3.11.

== Feature: CMS-PSU-API enriching responses

From now on, responses for 3 endpoints in CMS-PSU-API were enriched:

 - `GET /psu-api/v1/payment/redirect/{redirect-id}`
 - `GET /psu-api/v1/payment/cancellation/redirect/{redirect-id}`
 - `GET /psu-api/v1/ais/consent/redirect/{redirect-id}`

Now payment endpoints return the following: payment object, payment ID, authorisation ID, TPP payment redirect URIs, status change timestamp and TPP info. And the AIS consent endpoint returns: consent object, consent ID, authorisation ID, TPP consent redirect URIs, status change timestamp and TPP info.

== Refactor: Event API refactoring

Event functionality is now implemented in separate module and has `Events-XS2A-API` and `Events-ASPSP-API` modules accordingly. Current behavior is preserved.
