= Release notes v.5.7

== Table of Contents
* Support confirmation of authorisation
* Update Account Owner Name Service
* Bugfix: Oracle incompatibility in AisConsentJpaRepository
* Store and export data from CMS for PSU related headers
* Bugfix: Domain Validation failure on certificate compare

== Support confirmation of authorisation

New feature is added - ability to confirm authorisations for payment (initiation and
cancellation) and for AIS consent. The feature is enabled by setting the new property in ASPSP profile: `authorisationConfirmationRequestMandated = true`. This works only for Redirect approach and also new status of authorisation appears - `UNCONFIRMED`. First, the authorisation confirmation data should be provided through CMS-PSU-API for the definite authorisation. Then it is stored in CMS and to finalise this authorisation one should provide the same data to XS2A endpoints depending on the flow (AIS/PIS/PIS cancellation):

* PUT `/v1/consents/{consent_id}/authorisations/{authorisation_id}`;
* PUT `/v1/{payment_service}/{payment_product}/{payment_id}/authorisations/{authorisation_id}`;
* PUT `/v1/{payment_service}/{payment_product}/{payment_id}/cancellation-authorisations/{authorisation_id}`).

If the authorisation confirmation data differs - authorisation receives status `FAILED`. In case of the same confirmation data - authorisation becomes `FINALISED`. Data comparison can be implemented on XS2A side (ASPSP profile property `authorisationConfirmationCheckByXs2a` must be `true`) or at the ASPSP side (`authorisationConfirmationCheckByXs2a` must be `false`).

== Update Account Owner Name Service

From now on, Account Owner Name Service has several changes:

* In Consent request body "additionalAccountInformation" field was renamed to "additionalInformation";
* In Consent request body fields "availableAccounts", "availableAccountsWithBalance" and "allPsd2" may have additional value "allAccountsWithOwnerName";
* Field "ownerAddress" was removed from Consent request body and Account Details;

Also if TPP creates consent with additional information and the ASPSP doesn't support it (accountOwnerInformationSupported=false)
then TPP will receive HTTP 401 response code with message code "CONSENT_INVALID" and text message "An explicit consent of ownerName is not supported."

== Bugfix: Oracle incompatibility in AisConsentJpaRepository

From now on, database queries in AisConsentJpaRepository are fixed and don't throw any exception.

== Store and export data from CMS for PSU related headers

From now on, xs2a supports a new table `additional_psu_data` which saves additional,
psu-related, fields, such as `psu-ip-port`, `psu-user-agent`, `psu-geo-location`, `psu-accept`,
`psu-accept-charset`, `psu-accept-encoding`, `psu-accept-language`, `psu-http-method` and `psu-device-id`.
These fields are provided through initiating endpoints for AIS or PIS. Also, `psu-ip-address` is now persisted as well,
and saved inside of the `psu_data` table.

== Bugfix: Domain Validation failure on certificate compare

From now on, it is possible to use links to pages in TPP URI headers,
for example: http:\\test-bank.com\page.html. In this URI test-bank.com will be validated.
