= Release notes v.5.3

== Table of Contents

* Incorrect scaStatus for Start the authorisation request (redirect explicit PIS/AIS)
* Provide header Authorization in ContextData
* Feature: Extend CMS to store SCA method and TAN for Redirect approach
* Bugfix: PIIS consent status is being changed on implicit revocation
* Save payment transaction status given by ASPSP
* When bank returns PATC status for payment, multilevel flag in CMS should be set to true

== Incorrect scaStatus for Start the authorisation request (redirect explicit PIS/AIS)

From now on, if you try to start authorization process for payment or consent without PSU-ID header for  payment or
consent which was initiated with PSU-ID header, you’ll get scaStatus psuIdentified.

== Provide header Authorization in ContextData

From now on, there is a possibility to use header `Authorization` in XS2A requests, which stores the OAuth2 bearer token.
This token passes the SPI level inside the SpiContextData object.

== Feature: Extend CMS to store SCA method and TAN for Redirect approach

From now on, there is a possibility for online banking to send optional SCA method and optional authentication data (e.g. TAN) in CMS-PSU-API update authorisation status request (`PUT /psu-api/v1/payment/{payment-id}/authorisation/{authorisation-id}/status/{status}`
for payments and `PUT /psu-api/v1/ais/consent/{consent-id}/authorisation/{authorisation-id}/status/{status}` for AIS consents).
Data should be sent in JSON format:

[source,json]
----
{
	"authenticationMethodId": "SMS",
	"authenticationData": "123456"
}
----

Both fields are stored in CMS in 'ais_consent_authorization' and `pis_consent_authorization` tables.

== Bugfix: PIIS consent status is being changed on implicit revocation

From now on, implicit consent revocation on creating new PIIS consent will no longer change consent status to `REVOKED_BY_PSU` if its current status is finalised.

== Save payment transaction status given by ASPSP

From now on there is new endpoint in CMS-ASPSP-API: `PUT /aspsp-api/v1/pis/transaction-status/{payment-id}/status/{status}`,
where you can change payment's transaction status by payment id even if it is already finalised.

== When bank returns PATC status for payment, multilevel flag in CMS should be set to true

From now on, when bank returns `PATC` status for payment, multilevel flag in `pis_common_payment` table is
set to true.
