= Release notes v.8.1

== Table of Contents

* Fixed internal server error on `GET aspsp-api/v1/ais/consents/account/{account-id}` with oracle db
* Fixed deadlock while saving authentication methods for authorisation
* Added field charge bearer
* Added pagination for transactions
* Added debtorName field to get payment response

== Fixed internal server error on `GET aspsp-api/v1/ais/consents/account/{account-id}` with oracle db

From now on, endpoint `GET aspsp-api/v1/ais/consents/account/{account-id}` works correct with oracle db

== Fixed deadlock while saving authentication methods for authorisation

From now on, authentication methods for authorisation saving only in case they differ from already
saved one for same authorisation.

== Added field charge bearer

Added field charge bearer to `PaymentInitiationJson`, `PaymentInitiationWithStatusResponse`, `PaymentInitiationBulkElementJson`
and passed this field to spi level. From now on, `SpiSinglePayment` contains String field `chargeBearer`.
For validating this field according to bank requirements, extend payment validation on connector side.
Instruction how to do that one can find in `Extending payment validation.adoc`.

== Added pagination for transactions

From now on, pagination links passed from spi to get transaction list response.

== Added debtorName field to get payment response

Field `debtorName` was added to get payment response. Cms store original payment, and updated payment with
`debtorName` will be extracted from bank via spi call and passed to get payment response.
