= Release notes v.5.8

== Table of Contents

* Optional verification of URLs in headers according certificate domain
* Adopt data type Max512Text to Max500Text

== Optional verification of URLs in headers according certificate domain
From now on, URL validator is optional. And it can can be controlled by parameter `checkUriComplianceToDomainSupported` in ASPSP Profile.
When this parameter is `TRUE` then verification will check differences between domain from TPP Certificate and headers with URL (TPP-Redirect-URI, TPP-Nok-Redirect-URI and TPP-Notification-URI).
If TPP URIs are not compliant, then request is not rejected and response has tppMessages with text "TPP URIs are not compliant with the domain secured by the eIDAS QWAC certificate of the TPP in the field CN or SubjectAltName of the certificate".


== Adopt data type Max512Text to Max500Text

From now on, length of text fields in some TppMessage classes was changed from 512 characters to 500 (In accordance with Errata for BG specification)
