= Release notes v.13.5

== Table of Contents

* Finalisation of BG yaml file v.1.3.11 implementation

* Implemented passing of remittance related fields to SPI

* Fixed PIIS flow

* Bumped dependency versions

* Fixed bug in CardAccountModelMapper, postman tests updated

* Fixed bug in CMS AIS export flow

== Finalisation of BG yaml file v.1.3.11 implementation

XS2A completely implemented BG yaml v.1.3.11 changes, new fields of `CardTransaction` model (`valueDate` and `grandTotalAmount`)
are passed to SPI level (to `SpiCardTransaction` class).

== Implemented passing of remittance related fields to SPI

From now on all remittance related fields are being passed to SPI level

== Fixed PIIS flow

PIIS flow was fixed to handle properly funds confirmation requests for both types of PIIS consents (ASPSP and TPP), fixed TPP PIIS flow in case of multiaccount PSU,
added validation of proper consent type in AIS and PIIS services to prevent usage of PIIS Consent-ID in AIS flow and vise versa,
added proper error response in case of unsupported PIIS service. Postman environment variables and tests were updated.

== Bumped dependency versions

Version of hibernate-core was bumped up to 5.4.24.Final, liquibase - to 4.8.0

== Fixed bug in CardAccountModelMapper, postman tests updated

Added fix for proper mapping of multicurrency accounts, postman tests updated

== Fixed bug in CMS AIS export flow

Added fix for correct response from consents CMS export endpoints
