= Release notes v.5.6

== Table of Contents

* Added support of implicit subscription for resource status notifications
* Feature: Prevent modification of an established consent

== Added support of implicit subscription for resource status notifications

From now on, ASPSP profile has new property - `aspspNotificationsSupported` represented by list of possible values:

* SCA;
* PROCESS;
* LAST;
* NONE.

There is a possibility to set from 1 to 3 values simultaneously, or to set NONE if ASPSP doesn't support status
notifications. POST requests for initiating payment and creating AIS consent may use new headers: `TPP-Notification-URI`
(URI for notifications) and `TPP-Notification-Content-Preferred` (the list of desired notification modes).
The list of supported notification modes for AIS consents and payments are stored in CMS in new SQL tables - `ais_consent_tpp_ntfc`
and `payment_tpp_ntfc`. XS2A internal logic is able to provide response headers for upper mentioned POST requests:

* `ASPSP-Notification-Support` - boolean flag used to show if support of notification is enabled;
* `ASPSP-Notification-Content` - string with a list of used notification modes.

== Feature: Prevent modification of an established consent

From now on, when AIS consent changes status to `VALID`, all further modifications of these fields are rejected by CMS checksum
validation service:

* TPP account accesses;
* ASPSP account accesses;
* recurringIndicator;
* validUntil;
* frequencyPerDay;
* combinedServiceIndicator.

In other words, after AIS consent is in finalised status, its fields are not allowed to be changed in CMS anymore.
Neither by TPP nor by ASPSP side.

