= Release notes v.4.5

== Table of Contents

* Removed deprecated columns TppRedirectUri from TppInfo
* Removed deprecated `PsuIdData` from `confirmConsent`, `rejectConsent`, `revokeConsent` in `CmsPsuAisService`
* Refactoring: Extracted ASPSP Profile web-endpoints into separate module
* Bugfix: incorrect response for start authorisation request with password but without PSU-ID in header Explicit AIS/PIS
* Refactored `PisCommonPaymentServiceInternal`

== Removed deprecated columns TppRedirectUri from TppInfo

From now on, deprecated columns `redirect_uri`, `nok_redirect_uri`, `cancel_redirect_uri`,
`cancel_nok_redirect_uri` are removed from `tpp_info` table in CMS.

== Removed deprecated `PsuIdData` from `confirmConsent`, `rejectConsent`, `revokeConsent` in `CmsPsuAisService`

From now on, deprecated methods `confirmConsent`, `rejectConsent`, `revokeConsent` are removed from `CmsPsuAisService`.
And deprecated headers `psuId`, `psuIdType`, `psuCorporateId`, `psuCorporateIdType` are removed from methods
`confirmConsent`, `rejectConsent`, `revokeConsent` in `CmsPsuAisController` as well.

== Refactoring: Extracted ASPSP Profile web-endpoints into separate module

From now on, endpoints for accessing and updating ASPSP Profile are located in `aspsp-profile-web` module.

== Bugfix: incorrect response for start authorisation request with password but without PSU-ID in header Explicit AIS/PIS

From now on, when you try to start authorisation for payment/consent with password and without `PSU-ID` in header,
you'll receive the same response as it would be with `PSU-ID` in header.

== Refactored `PisCommonPaymentServiceInternal`

From now on, `PisCommonPaymentServiceInternal` is split into two services: `PisCommonPaymentServiceInternal`
and `PisAuthorisationServiceInternal`.
