= Release notes v.4.1

== Table of Contents

* Change yaml-generator to correct model Objects equals
* Bugfix: Wrong PSU-ID can authorise endpoints
* Bugfix: Don't provide `creditorAddress` field in get payment response if it was absent in initiate payment request
* Bugfix: Wrong `authorisation_id` can authorise
* Bugfix: Array "account" in Read Balances and Read Transaction List responses is empty for Global consent
* Refactor: Aggregate all messages sent to TPP to message bundle

== Change yaml-generator to correct model Objects equals

From now on, instances of generated models in `xs2a-server-api` module will correctly compare superclass properties in `equals` method.

== Wrong PSU-ID can authorise endpoints

From now on, PSU that is different from the PSU in authorisation can not update data on the authorisation resource.
This applies to the following endpoints:

* consent `PUT /v1/consents/{consentId}/authorisations/{authorisationId}`,
* payment `PUT /v1/{payment-service}/{payment-product}/{payment-id}/authorisations/{authorisation-id}`,
* payment cancellation `PUT /v1/{payment-service}/{payment-product}/{payment-id}/cancellation-authorisations/{cancellation-id}`.

== Bugfix: Don't provide `creditorAddress` field in get payment response if it was absent in initiate payment request

From now on, `creditorAddress` field is absent in get payment response `GET /v1/{payment-service}/{payment-product}/{paymentId}`
if it was not provided in initiate payment request `POST /v1/{payment-service}/{payment-product}`

== Bugfix: Wrong `authorisationId` can authorise

Fixed bug with updating authorisation by wrong `authorization_id`. From now on, endpoints below return `403 RESOURCE_UNKNOWN`:

* `PUT /v1/consents/{{consent_id}}/authorisations/{{authorisation_id}}`
* `PUT /v1/{{payment_service}}/{{payment_product}}/{{payment_id}}/authorisations/{{authorisation_id}}`
* `PUT /v1/{{payment_service}}/{{payment_product}}/{{payment_id}}/cancellation-authorisations/{{cancellation_id}}`

== Bugfix: Array "account" in Read Balances and Read Transaction List responses is empty for Global consent

From now on, array "account" in read balances `GET /v1/accounts/{account-id}/balances` and read transactions
`GET /v1/accounts/{account-id}/transactions` is not empty for global consent, and contains account references.

== Refactor: Aggregate all messages sent to TPP to message bundle

From now on all text messages for TPP are aggregated in `error_message.properties` file. These messages are executed by
`Psd2ErrorMapper`. Also from now on class `TppMessageInformation` has new array field `textParameters` for keeping
values, which should be inserted into message text placeholders for TPP from `error_message.properties`.
