= Release notes v.9.10

== Table of Contents

* Removed @NotNull from TppDomainValidator#validate
* Added additional query parameters for `/psu-api/v1/ais/consent/consents`
* Added validation certificate roles for PIIS consent v2
* Updated jackson version to 2.12.1

== Removed @NotNull from TppDomainValidator#validate

From now on, @NotNull is removed from TppDomainValidator#validate.

== Added additional query parameters for `/psu-api/v1/ais/consent/consents`

From now on, getting consent by PSU can be filtered by query parameters:

* `status` - list of consent statuses, i.e. status=VALID,EXPIRED
* `accountNumber` - list of account numbers, i.e. accountNumber=CH0900784152046193205,CH0900784152046193206

All of these query parameters are optional, if they are empty it will mean ALL.

== Added validation certificate roles for PIIS consent v2

From now on, certificate roles will be applied for all `/v2/consents/confirmation-of-funds/**` endpoints.

To enable certificate roles validation set flag `setting.common.checkTppRolesFromCertificateSupported: TRUE`

== Updated jackson version to 2.12.1

Fixed severe security vulnerability detected in com.fasterxml.jackson.core:jackson-databind < 2.12.1 defined in pom.xml.
