= Release notes v. 3.8

== Table of Contents
* Refactor: ASPSP consent data refactoring
* Feature: Only authorisation number is used to identify TPP
* Feature: CMS-PSU-API enriching responses
* Refactor: Event API refactoring
* Bugfix: Authorisation ID is missing in update PSU responses
* Refactor: removed SpiFrequencyCode enumerator
* Bugfix: TPP URIs are validated in REDIRECT approach only
* Feature: Add to events psuId from payments and consents

== Refactor: ASPSP consent data refactoring

From now on, the data in SPI level communication is changed. Before, we used `AspspConsentData` object to store the byte array of ASPSP consent data and this object was used in all SPI methods signature as a parameter.
After this refactoring, new provider is used instead of this object: `SpiAspspConsentDataProvider`. This provider is transferred from XS2A
to SPI level and can be used for storing (`updateAspspConsentData` method) and loading (`loadAspspConsentData` method) the ASPSP consent data.
So, now the SPI developers should change their connectors according to these changes: replace the `AspspConsentData` parameter with
`SpiAspspConsentDataProvider` parameter in the SPI implementation.
Also, field `aspspConsentData` and method `success()` were removed as deprecated from `SpiResponse` entity. Please use method `build()` instead.

Please note: from now on, the SPI developers are responsible for saving the ASPSP consent data to the database. XS2A-Core provides this possibility, but if no updateAspspConsentData call happens, no data will be saved.

== Feature: Only authorisation number is used to identify TPP

From now on, only authorisation number field in QWAC Certificate is used to identify TPP. Before, national authority id
was used for TPP identification as well. Column `authority_id` in `tpp_stop_list` table was marked as deprecated and will
be removed in version 3.11.

== Feature: CMS-PSU-API enriching responses

From now on, responses for 3 endpoints in CMS-PSU-API were enriched:

 - `GET /psu-api/v1/payment/redirect/{redirect-id}`
 - `GET /psu-api/v1/payment/cancellation/redirect/{redirect-id}`
 - `GET /psu-api/v1/ais/consent/redirect/{redirect-id}`

Now payment endpoints return the following: payment object, payment ID, authorisation ID, TPP payment redirect URIs, status change timestamp and TPP info. And the AIS consent endpoint returns: consent object, consent ID, authorisation ID, TPP consent redirect URIs, status change timestamp and TPP info.

== Refactor: Event API refactoring

Event functionality is now implemented in separate module and has `Events-XS2A-API` and `Events-ASPSP-API` modules accordingly. Current behavior is preserved.

== Bugfix: Authorisation ID is missing in update PSU responses

Authorisation ID was missing in the responses for POST requests of starting the authorisation with password
(`POST /v1/{payment_service}/{payment_product}/{payment_id}/authorisations` and `POST /v1/consents/{consent_id}/authorisations`).
Now this field is present in the upper responses while providing the PSU data in the request bodies.

== Refactor: removed SpiFrequencyCode enumerator

Enumerator SpiFrequencyCode was removed from the package `de.adorsys.psd2.xs2a.spi.domain.code`. New enumerator
`de.adorsys.psd2.xs2a.core.pis.FrequencyCode` should be used instead, it has the same values.

== Bugfix: TPP URIs are validated in REDIRECT approach only

From now on, TPP URIs are validated only for REDIRECT approach and for requests: payment initiation, payment cancellation and consent creation.


== Feature: Add to events psuId from payments and consents

From now on, response to the `Event objects between two dates` Request (`GET /aspsp-api/v1/events/`) from CMS-ASPSP-API contains psu data list.
If event does not contain psu data then this event will fetch psu data from payments or consents to which this event is dedicated.
