= Release notes v. 3.9

== Table of Contents
* Log events to stdout
* New internal request ID
* Extract PSU data for payment cancellation from authorisation request
* Downloading transactions supported
* Provided PSU Data from request to SPI in SpiContextData
* Validate only TPP-Authorisation-Number in TPP-info for PIIS
* Bugfix: one-off consent details can be read only once

== Log events to stdout

New event module `event-service-persist-log-impl` has been added with logging implementation of `event-service-persist-api`.
This module can be used in CMS instead of `event-service-persist-db-impl` in order to log events without saving them to the database.
All events are being written to a separate logger (`event-log`) at `INFO` logging level using `SLF4J`.

Additional configuration of `SLF4J`-compatible logging framework may be required in order to properly display event logs.
Default logging configuration provided in `cms-standalone-service` writes log records only to the console.

== New internal request ID

From now on, XS2A generates internal request ID (`InR-Id`) for each incoming request from TPP in order to uniquely identify requests.
Unlike the `X-Request-ID`, which is generated and provided by the TPP, `InR-Id` is guaranteed to be unique.
This internal request ID is now provided to the SPI inside the `de.adorsys.psd2.xs2a.spi.domain.SpiContextData`.
It was also added to the events, `access-log`, `request-log` and internal XS2A logs.

== Extract PSU data for payment cancellation from authorisation request

From now on, PSU Data is extracted from authorisation request instead of payment object.
During initiate payment cancellation PSU Data is empty when ContextData is sent to SPI.

== Downloading transactions supported

From now on, `GET /v1/accounts/{account-id}/transactions` endpoint may return download link, which can be used
by TPP for downloading transactions as a file. A new REST API `GET /v1/accounts/{account-id}/transactions/download/{download-id}`
was added to provide the download data.

For a SPI developer, `downloadId` field was added to `SpiTransactionReport.java` class, which should be filled, if transaction's
downloading should be supported. Also, a new method `requestTransactionsByDownloadLink` was added to `AccountSpi.java`, which
is invoked, when TPP tries to download transactions by the download link. This method's response contains binary java inputstream
as a source of controller response data.

== Provided PSU Data from request to SPI in SpiContextData

From now on, PSU Data is extracted from the request instead of the consent or payment objects.

== Validate only TPP-Authorisation-Number in TPP-info for PIIS

New column `tpp_authorisation_number` is added to `piis_consent` table.
From now on, if PIIS consent is stored in CMS (in profile `piisConsentSupported=true`) field `TPP-Authorisation-Number` will be stored as well and used for TPP INFO validation instead of the whole TPPInfo.
Field TppInfo is deprecated in `CreatePiisConsentRequest`.

== Bugfix: one-off consent details can be read only once

From now on, after creating one-off AIS consent, TPP is able to read all its information (accounts, balances, transactions)
only once and it doesn't depend on the `psu-ip-address` header presence in the request. This works only for one-off consents, i.e. `recurringIndicator = false`.
