= Release notes v.6.3

== Table of Contents

* Removed deprecated SPI constructors in `SpiAccountDetails`, `SpiCardAccountDetails`, `SpiCardTransaction` and `SpiTransaction`
* Removed unused methods in `PisCommonPaymentController`, `PisCommonPaymentServiceBase`, `PisCommonPaymentServiceInternalEncrypted`, `PisCommonPaymentServiceInternal`, `PisCommonPaymentServiceRemote`

== Removed deprecated SPI constructors in `SpiAccountDetails`, `SpiCardAccountDetails`, `SpiCardTransaction` and `SpiTransaction`

Deprecated SPI constructors were removed (`SpiAccountDetails`, `SpiCardAccountDetails`, `SpiCardTransaction` and `SpiTransaction`).

== Removed unused methods in `PisCommonPaymentController`, `PisCommonPaymentServiceBase`, `PisCommonPaymentServiceInternalEncrypted`, `PisCommonPaymentServiceInternal`, `PisCommonPaymentServiceRemote`

Removed unused method `updatePaymentCommonPaymentData` in `PisCommonPaymentController`.
Removed unused method `updateCommonPayment` in `PisCommonPaymentServiceBase`.
Removed unused method `updateCommonPayment` in `PisCommonPaymentServiceInternalEncrypted`.
Removed unused method `updateCommonPayment` in `PisCommonPaymentServiceInternal`.
Removed unused method `updateCommonPayment` in `PisCommonPaymentServiceRemote`.
Removed unused unit-tests for removed methods.
