= Release notes v.14.1

== Table of Contents

* Fixed error mapping

* Fixed links in PIS Cancellation

* Removed deprecated AisConsent and PiisConsentEntity entities, removed LazyMigrationService for consents

* Improved performance for consents export in CmsAspspAisExportApi

* Deprecated methods in AuthorisationSpi

== Fixed error mapping

Fixed 503 HTTP error code handling from SPI level.

== Fixed links in PIS Cancellation

From now on, PIS Authorisation links and PIS Cancellation Authorisation links have common building mechanism and conditions.

== Removed deprecated AisConsent and PiisConsentEntity entities, removed LazyMigrationService for consents

Deprecated entities AisConsent and PiisConsentEntity and corresponding LazyMigrationServices were removed completely from project,
liquibase migration was added.

== Improved performance for consents export in CmsAspspAisExportApi

Consents export logic was changed due to removal of needless LazyMigrationServices, as a result consents export performance was increased.

==  Deprecated methods in AuthorisationSpi

Two methods in AuthorisationSpi were marked as deprecated(`AuthorisationSpi.startAuthorisation` and `AuthorisationSpi.getScaStatus`).
Their signatures will be changed in release 14.4, new models `SpiScaApproach` and `SpiScaStatus`
will be used instead of old ones `ScaApproach` and `ScaStatus`.
