= Release notes v.4.3

== Table of Contents

* Incorrect scaStatus for Start the authorisation request (redirect explicit PIS/AIS)
* Bugfix: PIIS consent status is being changed on implicit revocation
* When bank returns PATC status for payment, multilevel flag in CMS should be set to true

== Incorrect scaStatus for Start the authorisation request (redirect explicit PIS/AIS)

From now on, if you try to start authorization process for payment or consent without PSU-ID header for payment or consent which was initiated with PSU-ID header, you’ll get scaStatus psuIdentified.

== Bugfix: PIIS consent status is being changed on implicit revocation

From now on, implicit consent revocation on creating new PIIS consent will no longer change consent status to `REVOKED_BY_PSU` if its current status is finalised.

== When bank returns PATC status for payment, multilevel flag in CMS should be set to true

From now on, when bank returns `PATC` status for payment, multilevel flag in `pis_common_payment` table is
set to true.
