
= Release notes v.9.7

== Table of Contents

* Adjust counting Consent usage for several booking statuses
* Fixed sonar alerts
* Added a psuMessage into Get SCA Status Response

== Adjust counting Consent usage for several booking statuses

From now on, the counting of Consent usage is adjusted.
Access to the Read Transactions endpoint is addressed several times with different
values for the bookingStatus as query parameter then this is counted as one access.
Access to the Read Transactions endpoint is addressed several times with different
values for the pageIndex as query parameter then this is counted as one access.

== Fixed sonar alerts

Sonar alerts were fixed for classes:

- AspspConsentData
- TppMessageInformation
- ExpirationException
- PisDayOfExecution
- TransactionStatus
- OtpFormat
- ValidationResult

== Added a psuMessage into Get SCA Status Response

From now on, getting SCA status response include `psuMessage` (optional) from ASPSP.
Moreover, obtaining the SCA status remained from the CMS and obtaining `psuMessage` and `trustedBeneficiaryFlag`
was combined and moved to SPI level.

New method `AuthorisationSpi#getScaStatus` was added to SPI interface.
Existing method `AuthorisationSpi#requestTrustedBeneficiaryFlag` was marked as deprecated and will be removed soon.
