= Release notes v.7.4

== Table of Contents

* Added Postman tests for `cms-psu-api` controllers
* Provided interfaces for CMS web controllers in `consent-aspsp-web`, `consent-psu-web` and `consent-xs2a-web`
* Created script to delete deprecated type of access `OWNER_ADDRESS` in `account_access` and `aspsp_account_access` tables

== Added Postman tests for `cms-psu-api` controllers

Added Postman tests for `cms-psu-api` controllers: `AspspConsentDataPsuApiController`, `CmsPsuAisController`, `CmsPsuPiisController`, `CmsPsuPisController`.

== Provided interfaces for CMS web controllers in `consent-aspsp-web`, `consent-psu-web` and `consent-xs2a-web`

Provided interfaces for CMS web controllers in `consent-aspsp-web`, `consent-psu-web` and `consent-xs2a-web`.

== Created script to delete deprecated type of access `OWNER_ADDRESS` in `account_access` and `aspsp_account_access` tables

Created script `0109-remove-deprecated-type-access-from-account-access-tables.xml` to delete deprecated type of access `OWNER_ADDRESS` in `account_access` and `aspsp_account_access` tables.
