= Release notes v.4.2

== Table of Contents

* Add integration test for embedded mode for XS2A
* Bugfix: the field `lastActionDate` was not updated in piis_consent DB table
* Remove TppRedirectUri from TppInfo
* Remove PSU Data from update consent status requests in cms-psu-api
* Check incoming requests to have required information
* Incorrect link in response to create consent authorisation request in Oauth SCA Redirect flow
* Bugfix: error on initiating payment with custom payment product and JSON body
* Bugfix: Array "account" in Read Balances and Read Transaction List responses is empty for Global consent
* Create common class for Jackson functionality
* Add Internal Request-ID (inr-id) as additional parameter in scaRedirect URI
* Use PaymentType enum instead of string values in Xs2aCreatePisAuthorisationRequest and Xs2aUpdatePisCommonPaymentPsuDataRequest
* Added special mapping for `dayOfExecution` in periodic payments
* Remove JsonReader duplicates

== Add integration test for embedded mode for XS2A

Integration test has been added for XS2A to ensure that application correctly starts with embedded CMS and ASPSP Profile.

== Bugfix: the field `lastActionDate` was not updated in piis_consent DB table

From now on, initial value is set to the field `lastActionDate` in case of PIIS consent creation. Also, new value is
set if the consent was revoked.

== Remove TppRedirectUri from TppInfo

From now on deprecated field `tppRedirectUri` is removed from `TppInfo`. And  fields `redirectUri`, `nokRedirectUri`,
`cancelRedirectUri`, `cancelNokRedirectUri` are removed from `TppInfoEntity`. Columns `redirect_uri`, `nok_redirect_uri`,
`cancel_redirect_uri`, `cancel_nok_redirect_uri` from `tpp_info table` will be removed in v.4.5.

== Remove PSU Data from update consent status requests in cms-psu-api

From now on parameter `PsuIdData` became deprecated in interface `CmsPsuAisService` methods: `confirmConsent`,
`rejectConsent`, `revokeConsent`. Also in `CmsPsuAisController` methods `confirmConsent`, `rejectConsent`,
`revokeConsent` headers `psuId`, `psuIdType`, `psuCorporateId`, `psuCorporateIdType` now are deprecated.
All this deprecated parameters will be removed in version 4.5.

== Check incoming requests to have required information
From now on, validation for update AIS, PIS and payment cancellation authorisation requests was added. It checks whether
the provided authorisation data matches current authorisation stage. In negative case, `SERVICE_INVALID_400` is returned.

== Incorrect link in response to create consent authorisation request in Oauth SCA Redirect flow

From now on, response to create consent authorisation request in Oauth SCA Redirect flow
`/v1/consents/{consentId}/authorisations` contains `scaOAuth` link instead of `scaRedirect` link.

== Bugfix: error on initiating payment with custom payment product and JSON body

From now on, there is a possibility to create a custom payment product in the ASPSP profile and then initiate payments of
such type with JSON body. As there is no common model for them - such payments will pass to SPI level with their bodies as
byte arrays.

== Array "account" in Read Balances and Read Transaction List responses is empty for Global consent

From now on, the field `account` in read balances `GET /v1/accounts/{account-id}/balances` and read transactions
`GET /v1/accounts/{account-id}/transactions` is not empty for global consent, and contains account reference.

== Create common class for Jackson functionality

From now on Jackson functionality from ObjectMapper and JsonConverter is united into Xs2aObjectMapper class in xs2a-object-mapper module.

== Add Internal Request-ID (inr-id) as additional parameter in scaRedirect URI

From now on, ASPSP is able to modify redirect URLs for consent, payment and payment cancellation  with new parameter `{inr-id}`.
This parameter will be filled with internal request ID during construction `scaRedirect` link.
Also pay attention, if authorisation is created explicitly, value of this parameter
will be fetched from previous request (consent creation, payment initiation or cancel payment).

== Use PaymentType enum instead of string values in Xs2aCreatePisAuthorisationRequest and Xs2aUpdatePisCommonPaymentPsuDataRequest

From now on, in classes `Xs2aCreatePisAuthorisationRequest` and `Xs2aUpdatePisCommonPaymentPsuDataRequest`
`paymentService` field is PaymentType enum instead of string.

== Added special mapping for `dayOfExecution` in periodic payments

From now on, while creating periodic payments, there is a possibility to pass the `dayOfExecution` value like `5` and
`05`. Both these variants will be passed to the SPI level (leading zero is ignored).

== Remove JsonReader duplicates

From now on there is only one JsonReader class located in json-reader module.
