= Release notes v.7.9

== Table of Contents

* Supported Funds Confirmation Consent in Decoupled approach with multilevel sca
* Fixed incorrect saving of owner_name_type and trusted_beneficiaries_type in consent table for piis consent
* Added a new optional header TPP-Rejection-NoFunds-Preferred
* Migrated to psd2-api 1.3.6 2020-08-14.yaml
* Changed types of remittance information structured properties in SpiTransaction and SpiSinglePayment

== Supported Funds Confirmation Consent in Decoupled approach with multilevel sca

From now on, funds confirmation consent decoupled flow is supported by xs2a.

== Fixed incorrect saving of owner_name_type and trusted_beneficiaries_type in consent table for piis consent

From now on, piis consent is saving with correct 'NONE' value of owner_name_type and trusted_beneficiaries_type
columns in consent table. All old incorrect 'ALL_AVAILABLE_ACCOUNTS' value were replaced with 'NONE'.

== Added a new optional header TPP-Rejection-NoFunds-Preferred

From now on, `TPP-Rejection-NoFunds-Preferred` is passed to spi level inside `SpiContextData`

== Migrated to psd2-api 1.3.6 2020-08-14.yaml

From now on, XS2A uses version `1.3.6 2020-08-14.yaml` of OpenAPI file provided by the Berlin Group.

==  Changed types of remittance information structured properties in SpiTransaction and SpiSinglePayment

In accordance with the changes to OpenAPI file 1.3.6 2020-08-14.yaml, types of `remittanceInformationStructured`
and `remittanceInformationStructuredArray` properties in `de.adorsys.psd2.xs2a.spi.domain.account.SpiTransaction` and
'de.adorsys.psd2.xs2a.spi.domain.payment.SpiSinglePayment' were changed:

- from `Remittance` to `String` for `remittanceInformationStructured`
- from `List<Remittance>` to `List<String>` for `remittanceInformationStructuredArray`
