= Release notes v.5.11

== Table of Contents
* Consent refactoring
* Update version of spring-data-jpa to 2.2.4.RELEASE

== Consent refactoring

From now on, consents are moved to `consent` table from `ais_consent` and do not have specific AIS consent data.
All specific information is stored as byte array in consent. There is a new column `consent_type` that describes its type.
Another table `consent_tpp_information` is created for storing tpp specific information.

New module `xs2a-core-consents` is responsible for models and mapper belonging to AIS specific consent data.

To support all operation with consent added `CmsConsentController`:

* `POST /v1/consent` - creates new consent
* `GET /v1/consent/{encrypted-consent-id}` - reads consent by ID
* `GET /v1/consent/{encrypted-consent-id}/status` - gets consent status by ID
* `PUT /v1/consent/{encrypted-consent-id}/status/{status}` - updates consent status by ID
* `DELETE /v1/consent/{encrypted-consent-id}/old-consents` - finds and terminates old consents for TPP and PSU by new consent ID
* `PUT /v1/consent/{encrypted-consent-id}/multilevel-sca` - updates requirement for multilevel SCA for consent

== Update version of spring-data-jpa to 2.2.4.RELEASE

Updated version of spring-data-jpa to 2.2.4.RELEASE. It led to updating following dependencies:

* spring 5.1.6 -> 5.2.3
* spring-boot 2.1.11 -> 2.2.4
