= Release notes v.7.8

== Table of Contents

* Implemented explicit authorisation for PIIS consents
* Implemented multilevel for PIIS consents
* Fixed incorrect consent type in PIIS Consent
* Adjusted CoF request with consent created by TPP
* Supported Funds Confirmation Consent in Embedded approach with multilevel sca
* Implemented Get Authorisation Sub-resource request for Funds Confirmation Consent
* Implemented Get SCA Status request for Funds Confirmation Consent

== Implemented explicit authorisation for PIIS consents

From now on, explicit authorisation for PIIS consent is supported in Redirect and Embedded approach.
To configure redirect url for PIIS consent use `piisRedirectUrlToAspsp` parameter in `redirectLinkToOnlineBanking` block in ASPSP Profile.

== Implemented multilevel SCA for PIIS consents

For account with multiple PSUs, now it is possible to execute multilevel SCA for each PSU.
Piis Consent response from spi `SpiInitiatePiisConsentResponse` contains boolean field `multilevelScaRequired` to inform XS2A
that this PIIS Consent requires multilevel SCA and there should be always explicit authorisation approach used.

== Fixed incorrect consent type in PIIS Consent

From now on, PIIS Consent type can have any of following values either `PIIS_ASPSP` or `PIIS_TPP`.

== Adjusted CoF request with consent created by TPP

From now on, TPP is able to make Confirmation of Funds request `POST /v1/funds-confirmations` with TPP consent by providing id of the consent in `Consent-Id` header.
In this case Confirmation of Funds Consent will be retrieved from CMS and will be passed to the SPI level.

== Supported Funds Confirmation Consent in Embedded approach with multilevel sca

From now on, Funds Confirmation Consent in Embedded approach is supported by xs2a.

Also type of field `account` in `SpiPiisConsent` was changed from `AccountReference` to `SpiAccountReference`.
And type of `psuData` field was changed from `SpiPsuData` to `List<SpiPsuData> psuData`.

=== Implemented Get Authorisation Sub-resource request for Funds Confirmation Consent

From now on, endpoint `GET /v2/consents/confirmation-of-funds/{consentId}/authorisations` is implemented
and gives response with authorisation identifications list.

=== Implemented Get SCA Status request for Funds Confirmation Consent

From now on, endpoint `GET /v2/consents/confirmation-of-funds/{consentId}/authorisations/{authorisationId}`
is implemented and gives response with sca status of piis consent authorisation.
