= Release notes v.8.5

== Table of Contents

* Fixed pagination for getting consents by account id
* Fixed - Optional "instance-id" in "scaRedirect"
* Added field `otherAccountIdentification` to AccountReference
* Fixed TPP stop list saving data into DB
* Fixed sonar alerts
* Extracted methods for field max length check from AbstractBodyValidatorImpl into separate class
* Fixed performance issue with CMS scheduler tasks
* Added page information to `CMS-ASPSP-API` export responses

== Fixed pagination for getting consents by account id

From now on, pagination on `GET aspsp-api/v1/ais/consents/account/{account-id}` works correctly
with expected items on page.

== Fixed - Optional "instance-id" in "scaRedirect"

From now on, `{instance-id}` placeholder in redirect link will be replaced with `instance-id` in REDIRECT approach.

== Added field `otherAccountIdentification` to AccountReference

From now on, AccountReference contains field `otherAccountIdentification` for other account identifier.

== Fixed TPP stop list saving data into DB

From now on, tpp stop list saved into database as expected.

== Fixed sonar alerts

Sonar alerts were fixed for classes:

- CmsAspspStopListControllerIT
- CmsAspspTppInfoControllerIT
- PiisConsentIT
- CmsAspspEventControllerIT
- CmsAspspPiisControllerIT
- CmsAspspPiisExportControllerIT
- CmsAspspPisExportControllerIT
- CmsAspspPisTransactionControllerIT
- CmsAspspPsuConsentManagementControllerIT
- CommonAspspProfileSetting
- AspspProfileUpdateControllerTest
- BankProfileReadingService
- AspspProfileUpdateServiceImplTest
- OldBankProfileSetting
- WebConfig
- AspspProfileController
- CertificateControllerTest
- ExportUtil

== Extracted methods for field max length check from AbstractBodyValidatorImpl into separate class

From now on, there is separate FieldLengthValidator for max length checks.

== Fixed performance issue with CMS scheduler tasks

From now on, database requests which need data from ASPSP profile perform page by page.
Configuration property that defines page size  is `xs2a.cms.scheduler.processing.page-size` (default value - 100).
The rest database requests (get/update) were combined into one (update).

== Added page information to `CMS-ASPSP-API` export responses

From now on, all `CMS-ASPSP-API` exporting responses will contain page information:

```
{
"data": [requested data],
"pageInfo": {
   "pageIndex": 1,
   "itemsPerPage": 20,
   "totalItems": 1234
    }
}
```
where `data` it is a list of requested objects and `pageInfo` - page information.
Default values for request parameters are `pageIndex` - 0, `itemsPerPage` - 20.
