= Release notes v.5.8

== Table of Contents
* Move AuthenticationObject to xs2a-core
* Feature: Add new data attribute instructionIdentification for all standard payment types
* Bugfix: PIIS request not filtered by TPP consent

== Move AuthenticationObject to xs2a-core

Usages of `Xs2aAuthenticationObject` and `SpiAuthenticationObject` were substituted with `de.adorsys.psd2.xs2a.core.authorisation.AuthenticationObject`

== Feature: Add new data attribute instructionIdentification for all standard payment types

From now on, `instructionIdentification` field was added to all standard payment types.
Also in case `instructionIdentification` field exceeds the maximum length of 35 symbols TPP will receive `400 Bad Request` error with `FORMAT_ERROR` code.
New `instructionIdentification` field is stored in CMS database and is provided to SPI level.

== Bugfix: PIIS request not filtered by TPP consent

From now on, PIIS consents are correctly filtered by TPP during Funds Confirmation Request (`POST /v1/funds-confirmations`).
