= Release notes v.4.3

== Table of Contents

* Incorrect scaStatus for Start the authorisation request (redirect explicit PIS/AIS)
* Bugfix: PIIS consent status is being changed on implicit revocation
* When bank returns PATC status for payment, multilevel flag in CMS should be set to true
* Fixed typos in PSD2 yaml file
* Add statuses to logs

== Incorrect scaStatus for Start the authorisation request (redirect explicit PIS/AIS)

From now on, if you try to start authorization process for payment or consent without PSU-ID header for payment or consent which was initiated with PSU-ID header, you’ll get scaStatus psuIdentified.

== Bugfix: PIIS consent status is being changed on implicit revocation

From now on, implicit consent revocation on creating new PIIS consent will no longer change consent status to `REVOKED_BY_PSU` if its current status is finalised.

== When bank returns PATC status for payment, multilevel flag in CMS should be set to true

From now on, when bank returns `PATC` status for payment, multilevel flag in `pis_common_payment` table is
set to true.

== Fixed typos in PSD2 yaml file

All typos were fixed in BerlinGroup PSD2 yaml file. Also, all `description` fields were formatted in the same style.

== Add statuses to logs

From now on, `consentStatus`, `paymentStatus` and `scaStatus` values are being logged to `access-log`
for all AIS and PIS endpoints, if they were involved in the request.
