= Release notes v.11.9

== Table of Contents

* BG errata 1.3.9 changes implemented

* Refactored `Xs2aConsentService#createConsentAuthorisation`

* Added validation of payment type to CmsPsuPisApi#updatePayment

* Renamed methods getCardAccount, readCardAccount in CardAccountsAPI

* Cleaned payment links for pure Decoupled approach

== BG errata 1.3.9 changes implemented

* New models were added:

** `ExchangeRateTypeCode`

* Changes were made in models:
|===
| Classname | Changes

| CardAccountDetails | type of field  `String` `details` changed to Max1000Text
| CardTransaction | type of field  `String` `transactionDetails` changed to Max1000Text
| PaymentExchangeRate | type of field  `String` `unitCurrency` changed to CurrencyCode;
 type of field  `String` `contractIdentification` changed to Max35Text;
 type of field  `rateType` changed from `RateTypeEnum` to `ExchangeRateTypeCode`
| MessageCode202InitiationStatus | renamed to `MessageCode200InitiationStatus`

|===

== Refactored Xs2aConsentService#createConsentAuthorisation method

`Xs2aConsentService#createConsentAuthorisation` method signature changed from
(String, String, ScaApproach, ScaStatus, PsuIdData) to (String, CreateAuthorisationRequest), refactored inheritance structure for `AbstractConsentAuthorizationService`

== Added validation of payment type to CmsPsuPisApi#updatePayment

From now on validation of `paymentService` parameter is performed in `CmsPsuPisApi`#`updatePayment`.

== Renamed methods getCardAccount, readCardAccount in CardAccountsAPI

Methods getCardAccount, readCardAccount in CardAccountsAPI renamed into getCardAccountList and readCardAccountDetails

== Cleaned payment links for pure Decoupled approach

From now on authorisation links for create payment request and start payment authorisation request in pure decoupled
approach are removed from responses
