= Release notes v.5.2

== Table of Contents

* Add integration test for embedded mode for XS2A
* Bugfix: the field `lastActionDate` was not updated in piis_consent DB table
* Remove redundant request to delete ASPSP consent data on consent creation
* Create Bulk Payment validators
* Remove TppRedirectUri from TppInfo
* Remove redundant request to retrieve the consent from the database on consent creation
* Support country specific extensions for payments in the ASPSP profile
* Support Additional Account Information in AIS
* Check incoming requests to have required information

== Add integration test for embedded mode for XS2A

Integration test has been added for XS2A to ensure that application correctly starts with embedded CMS and ASPSP Profile.

== Bugfix: the field `lastActionDate` was not updated in piis_consent DB table

From now on, initial value is set to the field `lastActionDate` in case of PIIS consent creation.
Also, new value is set if the consent was revoked.

== Remove redundant request to delete ASPSP consent data on consent creation

From now on, XS2A won't try to delete ASPSP consent data in CMS for newly created AIS consent before the consent was passed to SPI.

== Create Bulk Payment validators

From now on all fields of bulk payments are validated according to specification.

== Remove TppRedirectUri from TppInfo

From now on deprecated field `tppRedirectUri` is removed from `TppInfo`. And  fields `redirectUri`, `nokRedirectUri`,
`cancelRedirectUri`, `cancelNokRedirectUri` are removed from `TppInfoEntity`. Columns `redirect_uri`, `nok_redirect_uri`,
`cancel_redirect_uri`, `cancel_nok_redirect_uri` from `tpp_info table` will be removed in v.4.5.

== Remove redundant request to retrieve the consent from the database on consent creation

From now on, XS2A won't retrieve AIS consent from the CMS immediately after its creation.

== Support country specific extensions for payments in the ASPSP profile

From now on, ASPSP is able to configure payment for different countries `countryValidationSupported` property in PIS block.
The configuration parameter takes country as ISO 3166-1 alpha-2 code (DE, AT, UA, etc). Germany (DE) is supported by default and Austria (AT) is available to choose from.
To extend existing configuration register custom implementation in `CountryPaymentValidatorResolver` for new country based on default one `DefaultPaymentValidationConfigImpl`.
Previous validation payment configuration in `application.properties` file has been removed.

== Support Additional Account Information in AIS

From now on, Additional Account Information is supported in AIS. To activate its support set property `accountOwnerInformationSupported` in APSPS profile to "TRUE".
After that, if TPP asks for additional account information during consent creation process it will be present in `SpiAdditionalInformationAccess` field in `SpiAccountConsent` object.
Based on this information, when TPP makes request for retrieving information about PSU account (`GET /v1/accounts` or `GET /v1/accounts/{account-id}`),
ASPSP can provide additional information in `ownerName` and `ownerAddress` fields in `SpiAccountDetails` object.

== Check incoming requests to have required information
From now on, validation for update AIS, PIS and payment cancellation authorisation requests was added. It checks whether
the provided authorisation data matches current authorisation stage. In negative case, `SERVICE_INVALID_400` is returned.
