= Release notes v.11.10

== Table of Contents

* Refactored scheduler for Non-recurring consent expiration task, fixed flow for NotConfirmedConsentExpirationScheduleTask

* Cleaned AIS consent links for pure Decoupled approach

* Cleaned PIIS consent links for pure Decoupled approach

* Cleaned Payment Cancellation links for pure Decoupled approach

==  Refactored scheduler for Non-recurring consent expiration task, fixed flow for NotConfirmedConsentExpirationScheduleTask

Schedulers for Non-recurring consent expiration task and Not Confirmed Consent Expiration task are recommended to be run separately with at least 15 min interval
to avoid of database inner locks. Fixed bug in NotConfirmedConsentExpirationScheduleTask flow as a result all not confirmed consents are now expiring according to ASPSP profile settings.

== Cleaned AIS consent links for pure Decoupled approach

From now on, authorisation links for create AIS consent request and start AIS consent authorisation request in pure decoupled
approach implicit mode are removed from responses

== Cleaned PIIS consent links for pure Decoupled approach

From now on, authorisation links for create PIIS consent request and start PIIS consent authorisation request in pure decoupled
approach implicit mode are removed from responses

== Cleaned Payment Cancellation links for pure Decoupled approach

From now on, authorisation links for payment cancellation request and payment cancellation authorisation request in pure decoupled
approach implicit mode are removed from responses
