/**
 * XS2A REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: fpo@adorsys.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccountAccess } from './accountAccess';


/**
 * Response for the get account information consent request by consent Id
 */
export interface AccountConsent {
    /**
     * Access
     */
    access: AccountAccess;
    /**
     * The following code values are permitted 'received', 'valid', 'rejected', 'expired', 'revoked by psu', 'terminated by tpp'. These values might be extended by ASPSP by more values.
     */
    consentStatus: AccountConsent.ConsentStatusEnum;
    /**
     * requested maximum frequency for an access per day. For a once-off access, this attribute is set to 1
     */
    frequencyPerDay: number;
    /**
     * This date is containing the date of the last action on the consent object either through the XS2A interface or the PSU/ASPSP interface having an impact on the status.
     */
    lastActionDate: string;
    /**
     * 'true', if the consent is for recurring access to the account data , 'false', if the consent is for one access to the account data
     */
    recurringIndicator: boolean;
    /**
     * valid until date for the requested consent. The content is the local ASPSP date in ISODate Format
     */
    validUntil: string;
}
export namespace AccountConsent {
    export type ConsentStatusEnum = 'RECEIVED' | 'REJECTED' | 'VALID' | 'REVOKED_BY_PSU' | 'EXPIRED' | 'TERMINATED_BY_TPP';
    export const ConsentStatusEnum = {
        RECEIVED: 'RECEIVED' as ConsentStatusEnum,
        REJECTED: 'REJECTED' as ConsentStatusEnum,
        VALID: 'VALID' as ConsentStatusEnum,
        REVOKEDBYPSU: 'REVOKED_BY_PSU' as ConsentStatusEnum,
        EXPIRED: 'EXPIRED' as ConsentStatusEnum,
        TERMINATEDBYTPP: 'TERMINATED_BY_TPP' as ConsentStatusEnum
    };
}
