/**
 * XS2A REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: fpo@adorsys.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccountReference } from './accountReference';
import { Amount } from './amount';


/**
 * Request for the Confirmation Funds
 */
export interface FundsConfirmationRequest {
    /**
     * Card Number of the card issued by the PIISP. Must be delivered if available.
     */
    cardNumber?: string;
    /**
     * Transaction amount to be checked within the funds check mechanism.
     */
    instructedAmount: Amount;
    /**
     * The merchant where the card is accepted as an information to the PSU.
     */
    payee?: string;
    /**
     * PSU’s account number.
     */
    psuAccount: AccountReference;
}
