{{ if and .Values.aspspProfile.enabled .Values.aspspProfile.route.enabled }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
{{- with .Values.aspspProfile.route.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  name: {{ template "psd2.fullname" . }}-aspspprofile
  labels:
{{ include "psd2.labels" . | indent 4 }}
    app.kubernetes.io/component: aspspProfile
spec:
  host: {{ tpl (required "aspspProfile.route.host must be defined" .Values.aspspProfile.route.host) . | quote }}
  port:
    targetPort: http
{{- with .Values.cms.route.tls }}
  tls:
{{ toYaml . | indent 4 }}
{{- end }}
  to:
    kind: Service
    name: {{ template "psd2.fullname" . }}-aspspprofile
    weight: 100
    wildcardPolicy: None
{{- end }}
