/**
 * XS2A REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: fpo@adorsys.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Amount } from './amount';


/**
 * Balance Information
 */
export interface Balance {
    /**
     * balance amount
     */
    balanceAmount: Amount;
    /**
     * balance type
     */
    balanceType: Balance.BalanceTypeEnum;
    /**
     * This data element might be used to indicate e.g. with the expected or booked balance that no action is known on the account, which is not yet booked.
     */
    lastChangeDateTime?: Date;
    /**
     * entryReference of the last commited transaction to support the TPP in identifying whether all PSU transactions are already known.
     */
    lastCommittedTransaction?: string;
    /**
     * Reference date of the balance
     */
    referenceDate?: string;
}
export namespace Balance {
    export type BalanceTypeEnum = 'CLOSING_BOOKED' | 'EXPECTED' | 'AUTHORISED' | 'OPENING_BOOKED' | 'INTERIM_AVAILABLE' | 'FORWARD_AVAILABLE' | 'NON_INVOICED' | 'AVAILABLE';
    export const BalanceTypeEnum = {
        CLOSINGBOOKED: 'CLOSING_BOOKED' as BalanceTypeEnum,
        EXPECTED: 'EXPECTED' as BalanceTypeEnum,
        AUTHORISED: 'AUTHORISED' as BalanceTypeEnum,
        OPENINGBOOKED: 'OPENING_BOOKED' as BalanceTypeEnum,
        INTERIMAVAILABLE: 'INTERIM_AVAILABLE' as BalanceTypeEnum,
        FORWARDAVAILABLE: 'FORWARD_AVAILABLE' as BalanceTypeEnum,
        NONINVOICED: 'NON_INVOICED' as BalanceTypeEnum,
        AVAILABLE: 'AVAILABLE' as BalanceTypeEnum
    };
}
