package de.adorsys.psd2.validator.certificate;

import java.io.IOException;

import org.junit.Assert;
import org.junit.Test;

import de.adorsys.psd2.validator.certificate.util.CertificateExtractorUtil;
import de.adorsys.psd2.validator.certificate.util.TppCertificateData;

public class CertificateExtractorUtilTest {

	@Test
	public void testExtractCertData() throws IOException {
		
		String encodedCert = "-----BEGIN CERTIFICATE-----MIID8TCCAtmgAwIBAgIEfAhFrzANBgkqhkiG9w0BAQsFADCBlDELMAkGA1UEBhMCREUxDzANBgNVBAgMBkhlc3NlbjESMBAGA1UEBwwJRnJhbmtmdXJ0MRUwEwYDVQQKDAxBdXRob3JpdHkgQ0ExCzAJBgNVBAsMAklUMSEwHwYDVQQDDBhBdXRob3JpdHkgQ0EgRG9tYWluIE5hbWUxGTAXBgkqhkiG9w0BCQEWCmNhQHRlc3QuZGUwHhcNMTgwNjMwMTgzNzE4WhcNMTgwNzE3MTkxNzQ3WjB6MRMwEQYDVQQDDApkb21haW5OYW1lMQwwCgYDVQQKDANvcmcxCzAJBgNVBAsMAm91MRAwDgYDVQQGEwdHZXJtYW55MQ8wDQYDVQQIDAZCYXllcm4xEjAQBgNVBAcMCU51cmVtYmVyZzERMA8GA1UEYQwIMTIzNDU5ODcwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCG8Pt7f6mRKKs87Xkyy3ibgZ2D4AXul7KWUka8KLtWi2m/L4f62rVx1de2I2wTZm9IFaIAc6JY7RmhrfPkv6+e0DGOTrSy68RAa2fhuvQtRn0MhNYpUJrnYF06NfLwZ4WqWHcf4rV0j+CRQn1A1F1gTGUPmYzzC3HuZd0hrM/KutxpuIbW9G4Vq6VkZsb/frLu01Y82yAL8gewWET3E276itowlT5CwQKzmt0uXJ3fRpnEr1zwiJiYCl7ws5M3NLL0DCkYBqmfEIK1rMYo/DDcjMtl8zpCVxwb+krKV0I0RGZbGNP9CTUK0tGXY7ivxEYbukEQWWQTL/67G6x+6d6FAgMBAAGjZDBiMGAGCCsGAQUFBwEDBFQwUgYGBACBmCcCMEgwOTARBgcEAIGYJwEBDAZQU1BfQVMwEQYHBACBmCcBAgwGUFNQX1BJMBEGBwQAgZgnAQMMBlBTUF9BSQwEQXV0aAwFMjM0MjIwDQYJKoZIhvcNAQELBQADggEBADuLMlRyopbjWiFvsiwv00I3kkn9wc3kIdmdCIb772wplmAPYjXBmxXDOTZ6zhp4AzKL0h3TqIg3J4iyX8+PMC9TFhPD/8a0kpvYuakZPGquVytrtpWKqY+J0GvSJ97bB3aa+gNs7dBCw1UYbPgbZ4PfIas9erTur2hl3rZvmnr01lct4d2fctQudDaaFkv6/aBBAIRf9Y9/q6+Y2Qqfn7HgZDSi98Uv4gKL5qbnTymvkqJ5CSb6nXjlJlI/sjsICYgm/7RQTKrSitYrVSsg+H5DqeQMk+nIqfBP6g9gqXy7QJ7cdgQQmgj2Ay2s3BTtcpMMHzr7SRV9uQT1pLJuma0=-----END CERTIFICATE-----";
		
		TppCertificateData extract = CertificateExtractorUtil.extract(encodedCert);
		
		Assert.assertTrue(extract.getPspRoles().size() == 3);
	}
}
