package de.adorsys.psd2.validator.certificate;

import java.io.IOException;

import org.junit.Assert;
import org.junit.Test;

import de.adorsys.psd2.validator.certificate.util.CertificateExtractorUtil;
import de.adorsys.psd2.validator.certificate.util.TppCertificateData;

public class CertificateExtractorUtilTest {

	@Test
	public void testExtractCertData() throws IOException {
		
		String encodedCert = "-----BEGIN CERTIFICATE-----MIIEBjCCAu6gAwIBAgIEejybVTANBgkqhkiG9w0BAQsFADCBlDELMAkGA1UEBhMCREUxDzANBgNVBAgMBkhlc3NlbjESMBAGA1UEBwwJRnJhbmtmdXJ0MRUwEwYDVQQKDAxBdXRob3JpdHkgQ0ExCzAJBgNVBAsMAklUMSEwHwYDVQQDDBhBdXRob3JpdHkgQ0EgRG9tYWluIE5hbWUxGTAXBgkqhkiG9w0BCQEWCmNhQHRlc3QuZGUwHhcNMTgwNzAyMTMzMDUyWhcNMTgwNzE5MTQxMTIxWjB6MRMwEQYDVQQDDApkb21haW5OYW1lMQwwCgYDVQQKDANvcmcxCzAJBgNVBAsMAm91MRAwDgYDVQQGEwdHZXJtYW55MQ8wDQYDVQQIDAZCYXllcm4xEjAQBgNVBAcMCU51cmVtYmVyZzERMA8GA1UEYQwIMTIzNDU5ODcwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCSYxs2Fhpkt0zweiLxiJ3+QwpENoiIyxtNKehU/oqc/V6mns8c2N1BgxDEUixAugf257zkwNn39PZKuV8S4T61GeT4UUvf5DySYvgI63XpbRF3hj0KJk/oZDanidFZ86X7kW7TcTetPX+AqGiCLQEIKbnyISh1qeij6SmMr2j6IXVBzSP9dnxif+nf2poj0kCAz69eCI2zHufz8VJuIf9RhFychuuPO/NCQXuKL7KFeEf5uLhDGPeGqeWs1EBCAECuBOSAOwX+uFwyn/Jw/HfzH0ZQtod7qaNs4/fvjtZOekOtBGYGFOaZlqNvmadiR9mMJTbSXmBY1A5DMdBGcPAzAgMBAAGjeTB3MHUGCCsGAQUFBwEDBGkwZwYGBACBmCcCMF0wTDARBgcEAIGYJwEBDAZQU1BfQVMwEQYHBACBmCcBAgwGUFNQX1BJMBEGBwQAgZgnAQMMBlBTUF9BSTARBgcEAIGYJwEEDAZQU1BfSUMMBEF1dGgMB0dlcm1hbnkwDQYJKoZIhvcNAQELBQADggEBAKXgO8FvKBmTOGn2gWlasZtSsIWbzexR0IMU1AuGNmkMF2BGEkBTQJ1bGpCd5+eBVUkbIQkxP0Oqyb/moNty/7c9gym1GpEzZ5Cs1Zgtne8EnOKh8sGtI9L0AFVSTFHPHt9qj4o5TMgzdU9Q4cq4bq9bSZiwo3btwgIkBn7yetvfo8fSADBSYwOlqUAv+mROjEID772owEOgn0fLZmlIdZl8rpYQlzbHpcvlTTdnQiidjdO4Xln3+NIp7ifIfBUoCei0AP8rAFhq14GIE1YweY9efa1QPEm/a9EN3f22Psyd/jrQqnWVLsIJIEPVth3gdish6tHDfED1PpZVtMxKHqE=-----END CERTIFICATE-----";
		
		TppCertificateData extract = CertificateExtractorUtil.extract(encodedCert);
			
		Assert.assertTrue(extract.getPspRoles().size() == 4);
	}
}
