/**
 * XS2A REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: fpo@adorsys.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccountReference } from './accountReference';
import { Address } from './address';
import { Amount } from './amount';
import { PurposeCode } from './purposeCode';
import { Remittance } from './remittance';
import { TheBICAssociatedToTheAccount_ } from './theBICAssociatedToTheAccount_';


/**
 * Payment Initialisation Request
 */
export interface SinglePayments {
    /**
     * creditor account
     */
    creditorAccount: AccountReference;
    /**
     * creditor Address
     */
    creditorAddress?: Address;
    /**
     * creditor agent
     */
    creditorAgent?: TheBICAssociatedToTheAccount_;
    /**
     * creditor name
     */
    creditorName: string;
    /**
     * debtor account
     */
    debtorAccount: AccountReference;
    /**
     * end to end authentication
     */
    endToEndIdentification?: string;
    /**
     * instructed amount
     */
    instructedAmount: Amount;
    /**
     * purpose code
     */
    purposeCode?: PurposeCode;
    /**
     * remittance information structured
     */
    remittanceInformationStructured?: Remittance;
    /**
     * remittance information unstructured
     */
    remittanceInformationUnstructured?: string;
    /**
     * requested execution date
     */
    requestedExecutionDate?: string;
    /**
     * requested execution time
     */
    requestedExecutionTime?: Date;
    /**
     * ultimate creditor
     */
    ultimateCreditor?: string;
    /**
     * ultimate debtor
     */
    ultimateDebtor?: string;
}
