@startuml
actor PSU
entity TPP
entity XS2A
entity SPI
entity CMS
entity Online_banking
entity Core_banking
note right of CMS
For an Authorithation Call
CMS-PSU-API is used
end note
PSU->TPP: Initiate Payment Cancellation
activate TPP
activate PSU
TPP -> XS2A: REST Call Initiate Payment Cancellation request \n"DELETE /v1/payment-service/{payment-product} / {paymentId}"
activate XS2A
XS2A->SPI: Java Call SPIinitiatePaymentCancellation
activate SPI
|||
SPI-->XS2A: SpiPaymentCancellationResponse
deactivate SPI
note left of TPP
Depending on the payment-service, the payment- product
and the ASPSP's implementation,
this TPP call might be sufficient to cancel a payment.
If an authorisation of the payment cancellation
is mandated by the ASPSP,
a corresponding hyperlink will be contained
in the response message.
end note
alt paymentCancellationAuthorizationMandated = FALSE
|||
      XS2A-->TPP: Response "http Code: 204 successful\n{"transactionStatus": "CANC"}"
deactivate XS2A
|||
else paymentCancellationAuthorizationMandated = TRUE
|||
      XS2A-->TPP: Payment Cancellation Response\n"link startAuthorisation"\n"http Code: 202 successful"
|||
TPP->XS2A: REST Call Initiate Payment Cancellation authorisation \n"POST/v1/{payment-service }/{payment-product}/\n{paymentId}/cancellation-authorisations"
activate XS2A
|||
XS2A-->TPP:Start authorisation response\n"link_SCARedirect "
deactivate XS2A
TPP-->PSU: Feedback to the customer\nAuthorise the transaction
deactivate TPP
|||
PSU->Online_banking: PSU re-direct to an authorisation webpage of the ASPSP
deactivate PSU
activate Online_banking
|||
Online_banking->CMS: REST Call GetPaymentByRedirectIdForCancellation\n"GET/psu-api/v1/payment/cancellation/redirect/{redirect-id}"
activate CMS
|||
CMS-->Online_banking: CmsPaymentResponse
|||
Online_banking->CMS: REST Call UpdatePsuIdPayment\n"PUT/psu-api/v1/payment/authorithation/\n{authorisation-id}/psu-data"
|||
CMS-->Online_banking: Response "http Codes: 200 successful or 400 error"
deactivate CMS
|||
Online_banking-->PSU: Authorisation Process Response
deactivate Online_banking
activate PSU
|||
PSU->Online_banking: The PSU Authorises the Cancellation
activate Online_banking
|||
Online_banking->CMS: REST Call UpdateAuthorisationStatus\n"PUT/psu-api/v1/payment/{payment-id}/authorisation/\n{authorisation-id}/status/{status}"
activate CMS
|||
CMS-->Online_banking: Response "http Codes: 200 successful or 400 error"
deactivate CMS
Online_banking->Core_banking: Execute Payment Cancellation
activate Core_banking
|||
Core_banking-->Online_banking: Response PaymentStatus
deactivate Core_banking
Online_banking->CMS: REST Call UpdatePaymentStatus\n"PUT/psu-api/v1/payment/{payment-id}/status/{status}"
activate CMS
|||
CMS-->Online_banking: Response "http Codes: 200 successful or 400 error"
deactivate CMS
|||
Online_banking-->PSU: Cancellation confirmed
deactivate Online_banking
|||
PSU->TPP: Redirect back to TPP
deactivate PSU
activate TPP
|||
|||
end
|||
TPP->XS2A: REST Call get payment status\n"GET/v1/{payment-service}/{paymentId}/status"
activate XS2A
|||
XS2A->CMS: REST Call GetPaymentById 
activate CMS
|||
CMS-->XS2A: Payment Object Response
deactivate CMS
|||
XS2A->SPI: Java Call SPI GetPaymentStatusByid
activate SPI
|||
SPI->Core_banking: GetPaymentStatusById
activate Core_banking
|||
Core_banking-->SPI: Transaction Status Response
deactivate Core_banking
|||
SPI-->XS2A: Transaction Status Response
deactivate SPI
|||
XS2A->CMS: REST Call UpdateTransactionStatus
activate CMS
|||
CMS-->XS2A: UpdateTransactionStatus Response
deactivate CMS
|||
XS2A-->TPP: Response: Transaction Status Response
deactivate XS2A
|||
TPP->XS2A: REST Call Get Payment Request "GET/v1/\n{payment-service}/{paymentId}"
deactivate TPP
activate XS2A
XS2A->CMS: REST Call GetPaymentById 
activate CMS
|||
CMS->XS2A: Payment Object Response
deactivate CMS
|||
XS2A->SPI: Java Call SPIGetPaymentbyId
activate SPI
|||
SPI->Core_banking: GetPaymentById
activate Core_banking
|||
Core_banking-->SPI: Payment Object Response
deactivate Core_banking
SPI-->XS2A: SpiSinglrPayment /\nSpiPeriodicPayment /\nSpiBulkPayment /\nSpiPaymentInfo
deactivate SPI
|||
XS2A->CMS: REST Call UpdatePayment
activate CMS
|||
CMS-->XS2A: UpdatePayment Response
deactivate CMS
|||
XS2A-->TPP: Get Payment Response
deactivate XS2A
activate TPP
|||
TPP->XS2A: REST Call get Cancellation Authorisaton Sub-Resouces Request\n"GET/v1/{payment-service}/{paymentId}/cancellation-authorithations"
activate XS2A
|||
XS2A->CMS: GetCancellationAuthorisationsByPaymentId
activate CMS
|||
CMS-->XS2A: GetCancellationAuthorisationsByPaymentId Response
deactivate CMS
XS2A-->TPP: Cancellation Authorisation Ids List
|||
TPP->XS2A: REST Call Get Cancellation Authorisation\n"GET/v1/{payment-service}/{payment-product}/\n{paymentId}/cancellation-authorisations/{cancellationId}"
XS2A->CMS: GetCancellationAuthorisationScaStatus
activate CMS
|||
CMS->XS2A: GetCancellationAuthorisationScaStatus Response
deactivate CMS
|||
XS2A-->TPP: Sca Status
|||
deactivate XS2A
deactivate TPP
|||

@enduml

