== Choosing the deployment layout
:toc-title:
//:imagesdir: usecases/diagrams
:toc: left
// horizontal line


=== Microservices Deployment

To deploy the XS2A service, one should use the following modules:

- ASPSP profile (static configuration for your ASPSP)
- Consent Management System (basic entities CRUD services and underlying database to store them)
- XS2A library itself (xs2a-impl, implementation of NextGenPSD2 Interface of Berlin Group)

Each of the specified components is a separate jar file (or several files) that can be deployed on web-server or in a docker container. Each
component can be started as a Spring Boot application and is written in Java 1.8 with Maven build system.

All of these can be deployed separately (using the network for communication) or as monolith in one server.
This setup depends on the current bank network configuration, data security and available hardware. More details can be
found at
xref:../GETTING_STARTED.adoc[Getting started]
page.

These 3 services are basic configuration and to integrate them into whole ASPSP system one should use SPI implementation
(connector between XS2A and ASPSP system) and ASPSP system.

When XS2A services are deployed as microservices there is risk of getting error (e.g. service unavailable) when we interacting with them.
In this case the request should be protected against unavailability of remote services by catching `ResourceAccessException` error.
When writing custom filters it's recommended to extend `GlobalAbstractExceptionFilter` class and write code in `doFilterInternalCustom` method that handles this error.

=== Embedded Deployment

=== Embedding XS2A Library

=== Embedding CMS Library

In order to start xs2a service with embedded CMS Library, one should use following annotations:

- `@EnableTransactionManagement`
- `@EntityScan({"de.adorsys.psd2.consent.domain", "de.adorsys.psd2.event.persist.entity"})`
- `@EnableJpaRepositories(basePackages = {"de.adorsys.psd2.consent.repository", "de.adorsys.psd2.event"})`
- `@ComponentScan(basePackages = {"de.adorsys.psd2.report"})`

Also one needs following dependencies:

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>

        <dependency>
            <groupId>de.adorsys.psd2</groupId>
            <artifactId>consent-management-lib</artifactId>
        </dependency>


        <dependency>
            <groupId>de.adorsys.psd2</groupId>
            <artifactId>cms-payment-support-impl</artifactId>
        </dependency>

        <dependency>
            <groupId>de.adorsys.psd2</groupId>
            <artifactId>consent-psu-web</artifactId>
        </dependency>

        <dependency>
            <groupId>de.adorsys.psd2</groupId>
            <artifactId>consent-aspsp-web</artifactId>
        </dependency>

        <dependency>
            <groupId>de.adorsys.psd2</groupId>
            <artifactId>consent-xs2a-web</artifactId>
        </dependency>

        <dependency>
            <groupId>de.adorsys.psd2</groupId>
            <artifactId>event-service-aspsp-impl</artifactId>
        </dependency>

        <dependency>
            <groupId>de.adorsys.psd2</groupId>
            <artifactId>cms-scheduler-service</artifactId>
        </dependency>

        <dependency>
            <groupId>de.adorsys.psd2</groupId>
            <artifactId>event-service-persist-db-impl</artifactId>
        </dependency>

And following properties:

- Datasource settings:

* `spring.datasource.url`
* `spring.datasource.username`
* `spring.datasource.password`

- JPA settings:

* `spring.jpa.properties.hibernate.default_schema`

*WARNING:*  `For encryption\decryption of aspsp data we use secret server key ('server_key') which is read from Environment variables.
So, before starting project you need to create environment variables and set value, as example:  'server_key=12345678' or run app with this parameter`

=== Embedding Profile library
