== Implementing SPI-API
:toc-title:
//:imagesdir: usecases/diagrams
:toc: left
// horizontal line

toc::[]

=== General requirements

SPI-API is used for connection between XS2A interface and ASPSP system, that's why this system is also called `connector`
and this word will be used in all chapters below.
XS2A provides interfaces in java (`de.adorsys.psd2.xs2a.spi.service` package), that should be implemented in the connector's code.
Basic responsibilities of the connector:

- Receive the input data from XS2A
- Provide this data to the ASPSP system (and/or add some business logic, if necessary)
- Retrieve the response from ASPSP system
- Provide the ASPSP system's response back to XS2A using `SpiResponse` class

Input data for the connector is provided from TPP through XS2A and some parameters in the interfaces' signatures
are the same for all of them:

- `SpiContextData` - the information about PSU and TPP
- `SpiAspspConsentDataProvider` - this service is used for providing ASPSP consent data to connector and ASPSP system

The response from the connector to XS2A is described in the next chapter.

=== SpiResponse

This class acts as the container for all responses from the connector to XS2A. It is a generic class and it uses builder
pattern to create the response. Main fields of the class:

- `T payload`
- `List<TppMessage> errors`

`payload` should be used to create successful response to XS2A. It should contain the entity which current SPI method deals with.
`errors` should be used in case the response fails. The list should contain at least one error element inside the `TppMessage`
container. It is possible to provide several errors, if necessary. Both `payload` and `errors` fields should use `build()`
method after them while creating the response. Typical usage of builder pattern for happy-path response:

`return SpiResponse.<SpiAuthorisationStatus>builder()
                   .payload(SpiAuthorisationStatus.SUCCESS)
                   .build();`

In this example the `SpiAuthorisationStatus` enumerator value is returned.

=== Work with ASPSP-Consent-Data object

=== Implementation of AccountSpi

The Interface is used for AIS consent accounts SPI implementation. The following methods should be implemented:

* *requestAccountList*;
* *requestAccountDetailForAccount*;
* *requestTransactionsForAccount*;
* *requestTransactionForAccountByTransactionId*;
* *requestBalancesForAccount*;
* *requestTransactionsByDownloadLink*.

The Method *requestTransactionsForAccount* provides a possibility to retrieve the list of bank transactions filtered by the period, AIS consent account ID and status.
It also provides the transaction list download ID, which can be used to download a file with the list of bank transactions.

The Method *requestTransactionsByDownloadLink* allows to download a list of bank transactions directly to the file.
It returns *SpiTransactionsDownloadResponse* object with the InputStream which contains the transaction list, filename (can be null) and the size of the payload in bytes (can be null also).

From the TPP side the download can be initiated by accessing new endpoint in account controller - *GET /v1/accounts/{account-id}/transactions/download/{download-id}*.
TPP should provide the AIS consent account ID and the download ID. As a response for accessing this endpoint, the TPP receives the stream with transaction list.

=== Implementation of AisConsentSpi

=== Providing account resources to consent

=== Implementation of FundsConfirmationSpi

=== Implementation of PaymentSpi(s)

*SPI* means Service Provider Interface that is an API intended to be implemented or extended by a third party.

We distinguish between following Interfaces: *SinglePaymentSpi*, *BulkPaymentSpi*, *PeriodicPaymentSpi*, *PaymentAuthorisationSpi*, *PaymentCancellationSpi*.

==== SinglePaymentSpi
The Interface is used for the single payment SPI implementation. The following Methods should be implemented:

* *initiatePayment*: aims to initiate a payment;
* *getPaymentById*: aims to read the payment by id;
* *getPaymentStatusById*: aims to read the payment status by id.

The method *initiatePayment* returns a positive or negative payment initiation response as a part of SpiResponse and contains the following:

* *contextData*: holder of call's context data (e.g. about psuData and tppInfo):


*psuData* contains data about PSU known in scope of the request:

|===
| Attribute | Type | Condition | Description

| psuId | String | Conditional | Client ID of the PSU in the ASPSP client interface
| psuIdType | String | Conditional | Type of the psuId, needed in scenarios where PSUs have several psuIds as access possibility
| psuCorporateId | String | Conditional | Identification of a corporate in the online Channels. Might be mandated in the ASPSP’s documentation. Only used in a corporate context
| psuCorporateIdType| String | Conditional | This is describing the type of the identification needed by the ASPSP to identify the psuCorporateId
|===

* *tppInfo*: contains information about the Tpp's certificate:
** "Registration number": example = "1234_registrationNumber";
** "Tpp name": example = "Tpp company";
** "National competent authority": example = "Bafin";
** "Redirect URI": URI of TPP, where the transaction flow shall be redirected to after a Redirect. Mandated for the *Redirect SCA Approach* (including OAuth2 SCA approach), specially when TPP-Redirect-preferred equals "true". It is recommended to always use this header field;
** "Nok redirect URI": if this URI is contained, the TPP is asking to redirect the transaction flow to this address instead of the TPP-Redirect-URI in case of a negative result of the redirect ScaMethod. This might be ignored by the ASPSP;
** *payment*: payment, that extends SpiPayment (Single Payment);
** *initialAspspConsentData*: Encrypted data is stored in the consent management system.

Response by the method *getPaymentById* returns payment as a part of SpiResponse and contains the following data:

* *contextData*;
* *payment*: Single Payment;
* *aspspConsentData*: Used on SPI level as a container of some binary data. Spi developers may save here necessary information, it is stored and encrypted in the consent. *This shall not use without consentId*.
Encrypted data is linked to a request. It may be null if consent does not contain such data, or request is not done from a workflow with a consent.

Response by the method *getPaymentStatusById* returns an object (with the transaction status) and contains the following:

* *contextData*;
* *payment*;
* *aspspConsentData*.

==== PeriodicPaymentSpi
The Interface is used for periodic payment for SPI implementation. The following Methods should be implemented:

* *initiatePayment*;
* *getPaymentById*;
* *getPaymentStatusById*.

The method *initiatePayment* returns a positive or negative payment initiation response as a part of SpiResponse and contains the following:

* *contextData*: holder of call's context data (e.g. about psuData and tppInfo);
* *payment*: Periodic Payment;
* *initialAspspConsentData*: Encrypted data is stored in the consent management system.

Response by the method *getPaymentById* returns payment as a part of SpiResponse and contains the following data:

* *contextData*;
* *payment*: Periodic Payment;
* *aspspConsentData*: Used on SPI level as a container of some binary data. Spi developers may save here necessary information, it is stored and encrypted in consent. *This shall not use without consentId*.
 Encrypted data is linked to a request. It may be null if consent does not contain such data, or request is not done from a workflow with a consent.

Response by the method *getPaymentStatusById* returns an object (with the transaction status) and contains the following:

* *contextData*;
* *payment*;
* *aspspConsentData*.

==== BulkPaymentSpi
The Interface is used for bulk payment for SPI implementation. The following Methods should be implemented:

* *initiatePayment*;
* *getPaymentById*;
* *getPaymentStatusById*.

The method *initiatePayment* returns a positive or negative payment initiation response as a part of SpiResponse and contains the following:

* *contextData*: holder of call's context data (e.g. about psuData and tppInfo);
* *payment*: Bulk Payment;
* *initialAspspConsentData*: Encrypted data to be stored in the consent management system.
*

Response by the methods *getPaymentById* returns payment as a part of SpiResponse and will contain the following data:

* *contextData*;
* *payment*: Bulk Payment;
* *aspspConsentData*: Used on SPI level as a container of some binary data. Spi developers may save here necessary information, it is stored and encrypted in consent. *This shall not use without consentId*.
Encrypted data is linked to a request. It may be null if consent does not contain such data, or request is not done from a workflow with a consent.

Response by the methods *getPaymentStatusById* returns an object (with the transaction status) and contains the following:

* *contextData*;
* *payment*;
* *aspspConsentData*.

==== PaymentAuthorisationSpi
The Interface is used while implementing payment authorisation flow on SPI level. This Interface is implemented by extending the *AuthorisationSPi*. The following Methods should be implemented:

* *authorisePsu*;
* *requestAvailableScaMethods*;
* *requestAuthorisationCode*.

The Method *authorisePsu* authorises psu and returns current (success or failure) authorisation status. *Should be used only with Embedded SCA Approach*. It contains following Data:

* *contextData*;
* *psuLoginData*: ASPSP identifier(s) of the psu, provided by TPP within this request;
* *password*: Psu's password;
* *businessObject*: payment object;
* *aspspConsentData*.

The Method *requestAvailableScaMethods* returns a list of SCA methods for the psu by its login. *Should be used only with the Embedded SCA Approach*. It contains following Data:

* *contextData*;
* *businessObject*;
* *aspspConsentData*.

The Mothod *requestAuthorisationCode* performs SCA depending on selected SCA method. *Should be used only with Embedded Approach*. Method returns a positive or negative response as a part of SpiResponse.
If the authentication method is unknow, then empty *SpiAuthorizationCoderesult* should be returned. It contains following Data:

* *contextData*;
* *businessObject*;
* *aspspConsentData*;
* *authenticationMethodId*: Id of a chosen SCA method.

In case of *Decoupled SCA Approach*, the method *startScaDecoupled* have to be implemented: method notifies a decoupled app about starting SCA. AuthorisationId is provided
to allow the app to access CMS. It returns a response object, contains a message from ASPSP to PSU, gives him instrctions regarding decoupled SCA starting. It contains the following data:

* *contextData*;
* *businessObject*;
* *aspspConsentData*;
* *authenticationMethodId*: for a decoupled SCA method within embedded approach;
* *authorisationId*: a unique identifier of authorisation process.

==== PaymentCancellationSpi
The Interface is used to cancel a payment. The following Methods should be implemented:

* *initiatePaymentCancellation*;
* *cancelPaymentWithoutSca*;
* *verifyScaAuthorisationAndCancelPayment*.

The Method *initiatePaymentCancellation* returns the payment cancellation response with information about transaction status and whether authorisation of the request is required. It contains the following data:

* *contextData*;
* *Payment*: payment to be cancelled;
* *aspspConsentData*.

The Method *cancelPaymentWithoutSca* is used by cancelling payment without performing SCA. Method returns a positive or negative payment cancellation response as part of spiResponse. It contains the following data:

* *contextData*;
* *Payment*: payment to be cancelled;
* *aspspConsentData*.

The Method *verifyScaAuthorisationAndCancelPayment* sends authorisation confirmation information (secure code or such) to ASPSP and, in case of successful validation, cancels payment at ASPSP.
It returns a positive or negative response as part of spiResponse. It contains the following data:

* *contextData*;
* *Payment* payment to be cancelled;
* *aspspConsentData*;
* *spiScaConfirmation*: payment cancellation confirmation information.

=== Strong Customer Authentication (SCA)
The Payment initiation depends heavily on the *Strong Customer Authentication (SCA)* approach implemented by the ASPSP. For now there are three Approaches implemented (REDIRECT, DECOUPLED and EMBEDDED).

==== SCA Approach DECOUPLED

==== SCA Approach EMBEDDED

==== SCA Approach REDIRECT
Prerequisites in case of *consent for payment initiation*:

* PSU initiated a payment by using TPP;
* PSU is authenticated via two factors: for example psuId and password;
* Each Payment initiation needs its consent.

When the Payment was initiated, it should be authorised by the PSU. In case of redirect approach the authorisation can be explicit or implicit.

*The explicit Start of the authorisation* process means that Payment initiation Request is followed by an explicit Request of the TPP to start the authorisation. It is followed by a redirection to the ASPSP SCA authorisation site.
A status request might be requested by the TPP after the session is redirected to the TPP's system. Redirect SCA Approach is used in case of *tppExplicitAuthorisationPreferred = true* and *signingBasketSupported = true* or in case of multilevel SCA.

* *tppExplicitAuthorisationPreferred*: value of tpp'choice of authorisation method;
* *signingBasketSupported*: indicates if signing basket is supported on the ASPSP profile. It returns _true_ if ASPSP supports signing basket, _false_ if doesn't.

In case of *implicit Start of the Authorisation process* the ASPSP needs no additional data from TPP. In this case, the redirection of the PSU browser session happens directly after the Payment Initiation Response.
Besides an SCA status request may be sent by the TPP to follow the SCA process. In this case, the authorisation is used based on *tppExplicitAuthorisationPreferred* and *signingBasketSupported values*:

* Implicit authorisation is used in all cases where *tppExplicitAuthorisationPreferred* or *signingBasketSupported not equals true*;
* Implicit approach *is impossible* in case of multilevel SCA.

For The Redirect Approach the developer needs to implement the following Methods:

* *createCommonPaymentAuthorisation*;
* *updateCommonPaymentPsuData*;
* *getAuthorisationSubResources*;
* *getAuthorisationScaStatus*;
* *getScaApproachServiceTypeProvider*.

The Method *createCommonPaymentAuthorisation* creates payment authorisation response and contains:

** *paymentId*: ASPSP identifier of a payment;
** *paymentType*: e.g. single payment, periodic payment, bulk payment;
** *psuData*: psuIdData container of authorisation data about PSU.

The Method *updateCommonPaymentPsuData* provides transporting data when updating consent psu data.
For the Redirect Approach this method is applicable for the selection of authentication methods, before choosing the actual SCA approach. It contains *request* with following data:

.Parameters
|===
| Attribute              |Type                 | Description

|paymentId               | String              | Resource identification of the related payment initiation
|authorisationId         | String              | Resource identification if the related payment initiation, Signing Basket or Consent authorisation sub-resource
|scaAuthenticationData   | String              |SCA authentication data, depending on the chosen authentication method
|psuData                 | String              | e.g. PsuId, PsuIdType, PsuCorporateId and PsuCorporateIdType
|password                | PSU Data            | Password of the psu
|authenticationMethodId  | String              | The authentication method ID as provided by the ASPSP
|scaStatus               | Sca Status          | e.g. psuIdentified
|paymentService          | String              | e.g. "payments", "bulk-payments" and "periodic-payments"
|paymentProduct          | String              | The related payment product of the payment initiation to be authorized
|updatePsuidentification | href Type           | The link to the payment initiation, which needs to be updated by the PSU identification if not delivered yet
|===

The Method *getAuthorisationSubResources* with the *paymentId* returns authorisation sub resources (e.g. list of authorisation ids).

The Method *getAuthorisationScaStatus* with *paymentId* (ASPSP identifier of the payment, associated with the authorisation) and *authorisationId* (authorisation identifier), returns SCA status.

_Example of Sca Status:_

* RECEIVED(“received”, false): if an authorisation or cancellation-authorisation resource has been created successfully.
* PSUIDENTIFIED(“psuIdentified”, false): if the PSU related to the authorisation or cancellation-authorisation resource has been identified.

The Method *getScaApproachServiceTypeProvider* provides SCA approach used in current service. It returns the ScaApproach *“Redirect”*.

===== Redirect Approach for Payment cancellation

The Method *createCommonPaymentCancellationAuthorisation* with *paymentId*, *paymentType* and *psudata* creates payment cancellation authorisation.

The Method  *getCancellationAuthorisationSubResources* with the *paymentId* returns authorisation sub resources.

The Method *updateCommonPaymentCancellationPsuData* updates the cancellation for the payment.

The Method *getCancellationAuthorisationScaStatus* with *PaymentId* and *CancellationId* (Resource identification of the related Payment Cancellation authorisation sub-resource) returns SCA status.

The Method *getScaApproachServiceTypeProvider* provides SCA approach used in current service. It returns the ScaApproach *“Redirect”*.
