== Setting up ASPSP Profile options
:toc-title:
//:imagesdir: usecases/diagrams
:toc: left
// horizontal line

=== Configuring Payment types and Payment products

==== How to add new custom payment-product

Xs2a has implementation to support custom payment-products which are different from Berlin Group list.
To use for example "new-payment-product", open *bank_profile.yaml* and add it to *supportedPaymentTypeAndProductMatrix*:
```
  SINGLE:
   - new-payment-product
  PERIODIC:
   - new-payment-product
  BULK:
   - new-payment-product
```

Custom payment-products will be passed to SPI level through the interface *de.adorsys.psd2.xs2a.spi.service.CommonPaymentSpi*
Therefore this interface should be implemented in your SPI-Connector.

== Configuring SCA redirect links

ASPSP is able to modify SCA redirect URLs for consent, payment and payment cancellation.

Redirect link for consent is constructed with `aisRedirectUrlToAspsp` parameter and can be configured with `{redirect-id}`, `{encrypted-consent-id}`, `{inr-id}` options.

Examples:

* "http://localhost/ais/{redirect-id}/{encrypted-consent-id}";
* "http://localhost:4200/ais/{redirect-id}/{encrypted-consent-id}/{inr-id}";
* "http://localhost:4200/ais/{redirect-id}".

Redirect link for payment is constructed with  `pisRedirectUrlToAspsp` parameter and can be configured with `{redirect-id}`, `{encrypted-payment-id}`, `{inr-id}` options.

Examples:

* "http://localhost/pis/{redirect-id}/{encrypted-payment-id}";
* "http://localhost:4200/pis/{redirect-id}/{encrypted-payment-id}/{inr-id}";
* "http://localhost:4200/pis/{redirect-id}".

Redirect link for payment cancellation is constructed with `pisPaymentCancellationRedirectUrlToAspsp` parameter and can be configured with the same options as for payment.

Examples:

* "http://localhost/pis/cancellation/{redirect-id}/{encrypted-payment-id}";
* "http://localhost:4200/pis/cancellation/{redirect-id}/{encrypted-payment-id}/{inr-id}";
* "http://localhost:4200/pis/cancellation/{redirect-id}".

All parameters are optional and can be omitted.

== Configuring SCA Redirect OAuth

XS2A supports several modes of redirect SCA approach:

* redirect (usual redirect approach);
* OAuth pre-step (TPP asks for token before initiation of the request);
* OAuth integrated (TPP asks for token after initiation of the request).

Switching between these modes can be done by changing the `scaRedirectFlow` field value in the ASPSP profile. Possible
values for it are:

* `REDIRECT`;
* `OAUTH_PRE_STEP`;
* `OAUTH`.

OAUTH and OAUTH_PRE_STEP modes require link to identity provider (IDP) in the ASPSP profile. This is the field `oauthConfigurationUrl`.
It should be used for accessing third-party applications for providing the token.

Pre-step mode flow is the following. If token is present, then pre-step OAuth was already applied by TPP and XS2A returns link `scaRedirect`
to redirect PSU to online-banking (or other authorisation server) for SCA. If token is absent in initial request, XS2A returns
error `401 UNAUTHORIZED` with text `Please retrieve token first from {oauthConfigurationUrl}`.

Integrated mode: if ASPSP supports integrated OAuth and token is absent in initial request for consent, payment and payment
cancellation, XS2A returns link `scaOauth` (based on `oauthConfigurationUrl` in profile) to redirect TPP to IDP. If token
is present, XS2A responds with error `403 FORBIDDEN` with text `Token is not valid for the addressed service/resource`.

=== Using debug interface
