== Setting up ASPSP Profile options
:toc-title:
//:imagesdir: usecases/diagrams
:toc: left
// horizontal line

=== Configuring Payment types and Payment products

==== How to add new custom payment-product

Xs2a has implementation to support custom payment-products which are different from Berlin Group list.
To use for example "new-payment-product", open *bank-profile.yaml* and add it to *supportedPaymentTypeAndProductMatrix*:
```
  SINGLE:
   - new-payment-product
  PERIODIC:
   - new-payment-product
  BULK:
   - new-payment-product
```

Custom payment-products will be passed to SPI level through the interface *de.adorsys.psd2.xs2a.spi.service.CommonPaymentSpi*
Therefore this interface should be implemented in your SPI-Connector.

== Configuring SCA redirect links

ASPSP is able to modify SCA redirect URLs for consent, payment and payment cancellation.

Redirect link for consent is constructed with `aisRedirectUrlToAspsp` parameter and can be configured with `{redirect-id}`, `{encrypted-consent-id}`, `{inr-id}` options.

Examples:

* "http://localhost/ais/{redirect-id}/{encrypted-consent-id}",
* "http://localhost:4200/ais/{redirect-id}/{encrypted-consent-id}/{inr-id}",
* "http://localhost:4200/ais/{redirect-id}"

Redirect link for payment is constructed with  `pisRedirectUrlToAspsp` parameter and can be configured with `{redirect-id}`, `{encrypted-payment-id}`, `{inr-id}` options.

Examples:

* "http://localhost/pis/{redirect-id}/{encrypted-payment-id}",
* "http://localhost:4200/pis/{redirect-id}/{encrypted-payment-id}/{inr-id}",
* "http://localhost:4200/pis/{redirect-id}"

Redirect link for payment cancellation is constructed with `pisPaymentCancellationRedirectUrlToAspsp` parameter and can be configured with the same options as for payment.

Examples:

* "http://localhost/pis/cancellation/{redirect-id}/{encrypted-payment-id}",
* "http://localhost:4200/pis/cancellation/{redirect-id}/{encrypted-payment-id}/{inr-id}",
* "http://localhost:4200/pis/cancellation/{redirect-id}"

All parameters are optional and can be omitted.

=== Using debug interface

The debug interface of the ASPSP profile enables the developer to update the list of supported SCA approaches and/or
ASPSP profile settings, temporarily during runtime. The changes won't be persisted, and only stored in the local
application cache. Thus, these endpoints are unviable for a production environment and should only be used for debugging,
as a more convenient way of changing the SCA approaches and/or the ASPSP profile settings.

The debug interface is enabled via configuring Spring Profiles. The according profile name is `debug_mode`.

The endpoints provided are the following:

- `POST /api/v1/aspsp-profile/for-debug/aspsp-settings` - Updates aspsp profile settings
* Requires the ASPSP profile settings, in JSON format
- `POST /api/v1/aspsp-profile/for-debug/sca-approaches` - Updates list of sca approaches
* Requires the SCA approaches, as separated Strings, in a JSON array
