/**
 * XS2A REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: fpo@adorsys.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AuthenticationObject } from './authenticationObject';
import { Links } from './links';


/**
 * Response for the create account information consent request in the Account service
 */
export interface CreateConsentResp {
    /**
     * A list of hyperlinks to be recognized by Tpp
     */
    links: Links;
    /**
     * Identification of the consent resource as it is used in the API structure
     */
    consentId?: string;
    /**
     * Authentication status of the consent
     */
    consentStatus: CreateConsentResp.ConsentStatusEnum;
    /**
     * Text to be displayed to the PSU, e.g. in a Decoupled SCA Approach
     */
    psuMessage?: string;
    /**
     * This data element might be contained, if SCA is required and if the PSU has a choice between different authentication methods. Depending on the risk management of the ASPSP this choice might be offered before or after the PSU has been identified with the first relevant factor, or if an access token is transported. If this data element is contained, then there is also an hyperlink of type 'selectAuthenticationMethods' contained in the response body.
     */
    scaMethods?: Array<AuthenticationObject>;
}
export namespace CreateConsentResp {
    export type ConsentStatusEnum = 'RECEIVED' | 'REJECTED' | 'VALID' | 'REVOKED_BY_PSU' | 'EXPIRED' | 'TERMINATED_BY_TPP';
    export const ConsentStatusEnum = {
        RECEIVED: 'RECEIVED' as ConsentStatusEnum,
        REJECTED: 'REJECTED' as ConsentStatusEnum,
        VALID: 'VALID' as ConsentStatusEnum,
        REVOKEDBYPSU: 'REVOKED_BY_PSU' as ConsentStatusEnum,
        EXPIRED: 'EXPIRED' as ConsentStatusEnum,
        TERMINATEDBYTPP: 'TERMINATED_BY_TPP' as ConsentStatusEnum
    };
}
