/**
 * XS2A REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: fpo@adorsys.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Links } from './links';
import { TransactionsCreditorResponse } from './transactionsCreditorResponse';


/**
 * Account Report
 */
export interface AccountReport {
    /**
     * Links: the following links might be used within this context:account link (mandatory)first_page_link (optional)second_page_link (optional)current_page_ link (optional)last_page_link (optional)
     */
    links: Links;
    /**
     * Booked TransactionsCreditorResponse
     */
    booked: Array<TransactionsCreditorResponse>;
    /**
     * Pending TransactionsCreditorResponse
     */
    pending?: Array<TransactionsCreditorResponse>;
}
