= How to report an issue to XS2A Team
:toc-title:
//:imagesdir: usecases/diagrams
:toc: left
// horizontal line

toc::[]


There are a few ways to connect XS2A Team if you think that our system behaves in an unexpected way or incorrect:

* Through https://github.com/adorsys/xs2a/issues[Github interface] - for external users of our open source projects.

* Through the https://adorsys.atlassian.net/jira/servicedesk/projects/PASD/issues[Service Desk interface] - for our customers.

Please raise a ticket, following this process:

1. Fill in the template:

* choose bug-ticket for report a bug;
* choose change request - for the suggestion of a new feature.

2. Try to be as precise as possible. The more information you provide, the faster analysis would be possible.
3. Describe current and expected behavior.
4. Specify the affected version.
5. Attach screenshots if needed.
6. Prioritise ticket. *Urgent (High)*- only if this problem blocks your further work and no workaround is possible (Please describe accordingly why).
7. Save a ticket and leave it unassigned. The ticket will be assigned to responsible team straight after analysis.


== Bug ticket workflow

Team will provide comments and feedback on the tickets.
