= Roadmap

Starting 1st of March 2020 XS2A-core Team is providing development within two branches:

*Stable branch 6.x*

Stable branch will contain bugfixing and possibly necessary changes to support mandatory endpoints defined by Berlin Group NextGenPSD2 Spec 1.3.6. Will be supported till 28.08.2020

*Development branch 7.x*

Development branch is oriented on implementation of new features and optional endpoints.
No backward compatibility with 6.x is guaranteed. Will be released as Stable version 8.x on 11.09.2020

[cols="3*.<"]
|===
|release date|version 6.x (Stable)|version 7.x (Development)

|31.07.2020|6.7|7.7

a|

a|

a|* All fixes and updates from v.6.7

* New feature: Add information about currency conversion to Payment Initiation response

* New feature: Add currency conversion related information to Update PSU Data response

* New feature: Add authorisation endpoints to CoF yaml

* New feature: Create interfaces in cms-psu-api for FundsConfirmationConsent

|14.08.2020|6.8|7.8

a|

a|

a|* All fixes and updates from v.6.8

* New feature: Revoke FundsConfirmationConsent

* New feature: FundsConfirmationConsent in Redirect approach with multilevel SCA

|28.08.2020|6.9|7.9

a|

a|

a|* All fixes and updates from v.6.9

* New feature: FundsConfirmationConsent in Embedded approach with multilevel SCA

* New feature: FundsConfirmationConsent in Decoupled approach with multilevel SCA

* New feature: Get Authorisation Sub-resource request for FundsConfirmationConsent

* New feature: Get SCA Status request for FundsConfirmationConsent 

|Further development| |

a|

a|

a|* New feature: Implement Read Card List

* New feature: Implement Read Card Details

* New feature: Implement Read Card Balances

* New feature: Implement Read Card Transaction List

* New feature: Add a new optional header TPP-Rejection-NoFunds-Preferred

* Move authorisation-related methods out of Xs2aAisConsentService and Xs2aPisCommonPaymentService

* New feature: Extension of possibility returning several camt.05x files in one zip file

* New feature: Create Resource Notification Push Service

* _Support of Signing Basket:_

- Create Signing Basket in CMS 

- Implement Establish Signing Basket request

- Implement Cancellation of Signing Baskets

- Support Signing Basket in Embedded approach with multilevel SCA

- Support Signing Basket in Decoupled approach with multilevel SCA

- Support Signing Basket in Redirect approach with multilevel SCA

- Implement Get Authorisation Sub-resources for Signing Baskets

- Create interfaces in cms-psu-api for Signing Basket

- Implement Get Signing Basket Status Request

- Implement Get Signing Basket Request 

- Implement Get SCA Status request for Signing Baskets

- Add calls to SPI for Signing Basket

|===