= Roadmap

Starting 1st of March 2020 XS2A-core Team is providing development within two branches:

*Stable branch 10.x*

Stable branch will contain bugfixing and possibly necessary changes to support mandatory endpoints defined by Berlin Group NextGenPSD2 Spec 1.3.8. Will be supported till 13.09.2021

*Development branch 11.x*

Development branch is oriented on implementation of new features and optional endpoints.
No backward compatibility with 10.x is guaranteed. Will be released as Stable version 12.x on 13.09.2021

[cols="5*.<"]
|====
|release date|version 8.x (Stable)|version 10.x (Stable)|version 11.x (Development)|XS2A extention (commercial)

|25.03.2021| 8.12| 10.0| 11.0| |

a| * Mock debtorName for get payment info

a| * All fixes and updates from v.8.0

* Add call to Spi for scaStatus on GET SCA Status request

a|* All fixes and updates from v.10.0

a| Signing Basket plugin for XS2A

a|

a|

a|

a|

a|

|*For future development*| |*10.x*|*11.x*| *XS2A extention (commercial)*

| | | | |Signing Basket plugin for XS2A

| | | | |Multiple consents plugin for XS2A

|====
