= Roadmap

Starting the 1st of August 2022 XS2A-core Team is providing development within two branches:

*Stable branch 14.x*

Stable branch will contain bugfixing and possibly necessary changes to support mandatory endpoints defined by Berlin Group NextGenPSD2 Spec 1.3.11 with all Errata files. Will be supported at least till 31.12.2022

*Development branch 15.x*

Development branch is oriented on implementation of new features and optional endpoints.
No backward compatibility with 14.x is guaranteed. Will be released as Stable version 16.x after 31.12.2022

[cols="1,3,3,2"]
|====
|release date|version 14.x (Stable)|version 15.x (Development)| XS2A extention (commercial)

|01.08.2022| 14.0| 15.0| |

a| * All fixes and updates from v.13.7:

** Bumped dependency versions

** Changed response body for Get transactions list request

** Migrated project to OpenAPI 3.0

** Changed logic for Confirmation of Funds requests

a| * All fixes and updates from v.14.0

a|

|*For future development*|  *14.x*| *15.x*| *XS2A extentions (commercial)*

| | | |AIS - current & savings accounts plugin

| | | |AIS - push notification services plugin

| | | |Signing Basket plugin

| | | |Multiple consents plugin

|====
