= Roadmap

Starting 1st of March 2020 XS2A-core Team is providing development within two branches:

*Stable branch 8.x*

Stable branch will contain bugfixing and possibly necessary changes to support mandatory endpoints defined by Berlin Group NextGenPSD2 Spec 1.3.6. Will be supported till 05.03.2021

*Development branch 9.x* - release date is not specified yet

Development branch is oriented on implementation of new features and optional endpoints.
No backward compatibility with 8.x is guaranteed. Will be released as Stable version 10.x on 19.03.2021

[cols="4*.<"]
|====
|release date|version 8.x (Stable)|version 9.x (Development)|XS2A extention (commercial)

|15.09.2020|8.0| |

a|

a|* Remove deprecated authorisation type AIS

a|

a|

|09.10.2020|8.1|9.0|

a|

a|* Update OAuth flow

* Set flag withBalance=true for Global Consent in CMS

a|* All fixes and updates from v.8.1

* Update CMS tables for Signing Basket plugin usage

a|

| |8.2|9.1|

a|

a|

a|

a|

| | | |Signing Basket plugin for XS2A

| | | |Single card account plugin for XS2A

| | | |Resource Notification Push Service

|====