= Roadmap

Starting 1st of March 2020 XS2A-core Team is providing development within two branches:

*Stable branch 6.x*

Stable branch will contain bugfixing and possibly necessary changes to support mandatory endpoints defined by Berlin Group NextGenPSD2 Spec 1.3.6. Will be supported till 28.08.2020

*Development branch 7.x*

Development branch is oriented on implementation of new features and optional endpoints.
No backward compatibility with 6.x is guaranteed. Will be released as Stable version 8.x on 11.09.2020

[cols="3*.<"]
|===
|release date|version 6.x (Stable)|version 7.x (Development)

|24.04.2020|6.3|7.3

a|

a| 

a|* All fixes and updates from v.6.3

* New feature: Implement Read the List of Trusted Beneficiaries

* New feature: Extend Response of GET SCA Status with trustedBeneficiary Flag according to BG specification 1.3.6

* New feature: Funds Confirmation consent support in Profile

* Change type of postCode to Max35Text

* Unification of Payment Canc auth-subresources by authorisationId instead of cancellationId

|08.05.2020|6.4|7.4

a|

a|

a|* All fixes and updates from v.6.4

* New feature: Add possibility to reject requests if TPP URIs are not compliant with Certificate domain

* New feature: Support yaml for Funds Confirmation consent

* New feature: Establish FundsConfirmationConsent

* Provide interfaces for CMS controllers for FundsConfirmationConsent

|22.05.2020|6.5|7.5

a|

a|

a|* All fixes and updates from v.6.5

* New feature: Create Funds Confirmation consent validator

* New feature: Get FundsConfirmationConsent Status + object

* New feature: Revoke FundsConfirmationConsent

|05.06.2020|6.6|7.6

a|

a|

a|* All fixes and updates from v.6.6

* New feature: FundsConfirmationConsent in Embedded approach with multilevel SCA

* New feature: FundsConfirmationConsent in Decoupled approach with multilevel SCA

|19.06.2020|6.7|7.7

a|

a|

a|* All fixes and updates from v.6.7

* New feature: Get Authorisation Sub-resource request for FundsConfirmationConsent

* New feature: Get SCA Status request for FundsConfirmationConsent 

|03.07.2020|6.8|7.8

a|

a|

a|* All fixes and updates from v.6.8

* New feature: Create interfaces in cms-psu-api for FundsConfirmationConsent

|17.07.2020|6.9|7.9

a|

a|

a|* All fixes and updates from v.6.9

* New feature: FundsConfirmationConsent in Redirect approach with multilevel SCA

|31.07.2020|6.10|7.10

a|

a|

a|* All fixes and updates from v.6.10

* New feature: Add a new optional header TPP-Rejection-NoFunds-Preferred

* Move authorisation-related methods out of Xs2aAisConsentService and Xs2aPisCommonPaymentService

|Further development| |

a|

a|

a|* New feature: Extension of possibility returning several camt.05x files in one zip file

* New feature: Create Resource Notification Push Service

* _Support of Signing Basket:_

- Create Signing Basket in CMS 

- Implement Establish Signing Basket request

- Implement Cancellation of Signing Baskets

- Support Signing Basket in Embedded approach with multilevel SCA

- Support Signing Basket in Decoupled approach with multilevel SCA

- Support Signing Basket in Redirect approach with multilevel SCA

- Implement Get Authorisation Sub-resources for Signing Baskets

- Create interfaces in cms-psu-api for Signing Basket

- Implement Get Signing Basket Status Request

- Implement Get Signing Basket Request 

- Implement Get SCA Status request for Signing Baskets

- Add calls to SPI for Signing Basket

|===