= Roadmap

Starting 1st of March 2020 XS2A-core Team is providing development within two branches:

*Stable branch 10.x*

Stable branch will contain bugfixing and possibly necessary changes to support mandatory endpoints defined by Berlin Group NextGenPSD2 Spec 1.3.8. Will be supported till 13.09.2021

*Development branch 11.x*

Development branch is oriented on implementation of new features and optional endpoints.
No backward compatibility with 10.x is guaranteed. Will be released as Stable version 12.x on 13.09.2021

[cols="5*.<"]
|====
|release date|version 6.x (Stable)|version 8.x (Stable)|version 9.x (Development)|XS2A extention (commercial)

|15.09.2020| | 8.0| |

a|

a|

a|* Remove deprecated authorisation type AIS

a|

a|

|12.10.2020|6.10| | |

a|

a|* Provide ScaStatus EXEMTED for user without SCA method

* Set flag withBalance=true for Global Consent in CMS

* Fix usage of embedded mode of connector

*  Fix cms aspsp api working with oracte db

* Remove obsolete property transaction.max-length

* Change type in PaymentSpi#verifyScaAuthorisationAndExecutePaymentWithPaymentResponse

* Fix deadlock during SCA execution

a|

a|

a|

|23.10.2020| |8.1|9.0|

a|

a|

a|* Update OAuth flow

* Set flag withBalance=true for Global Consent in CMS

* Fix internal server error on GET aspsp-api/v1/ais/consents/account/{account-id} with oracle db

* Fix deadlock while saving authentication methods for authorisation

* Add field chargeBearer for PIS

* Add pagination for transactions

* Add debtorName field to get payment response

* Add cms payment mapper resolver

* Add pageIndex and itemsPerPage to SpiTransactionReportParameters

* Remove obsolete property xs2a.application.ais.transaction.max-length

* Change (PaymentSpiPaymentCancellationSpi)#verifyScaAuthorisationAndExecutePaymentWithPaymentResponse response type

a|* All fixes and updates from v.8.1

* Update CMS tables for Signing Basket plugin usage

a|

|06.11.2020| |8.2|9.1|

a|

a|

a|* Add pagination at call GET /psu-api/v1/ais/consent/consents

a|* Add pagination at call GET /psu-api/v1/ais/consent/consents

a|
|20.11.2020| |8.3|9.2|

a|

a|

a|* Add Confirmation Code step to Oauth flow

* Bugfix: SCA redirect approach with authorisation confirmation request fails if no PSU-ID http header is available in request

* Bugfix: Change error when balance of account is not enough for payment execution

* Migrate to .yaml open API ver 1.3.8 2020-11-06v1

a|* All fixes and updates from v.8.3

a|

|03.12.2020| |8.4|9.3|

a|

a|

a| * Bugfix: POST on cancellation-authorisations immediately after payment-intiation brings NPE

* Bugfix: Add check for not valid payment status in PisPaymentController

* Bugfix: Add check for not valid payment status in PisCommonPaymentController

* Bugfix: Add check for not valid consent status in CmsConsentController

* Bugfix: Add check for not valid authorisation status in AuthorisationController

* Fix XS2A / Connector Security Hot Spots

* Increase code coverage for Connector

a| * All fixes and updates from v.8.4

a|

|17.12.2020| |8.5|9.4|

a|

a|

a| * Fix pagination for get consents by account id

* Fix perfomance issue

* Fix XS2A Security Hot Spots

* Fix bugs with TPP stop list in DB

* Add page information to CMS export requests


a| * All fixes and updates from v.8.5


a| Signing Basket plugin for XS2A

a|

a|

a|

a|

a|

|31.12.2020| |8.6|9.5|

a|

a|

a| * Fix perfomance issue

* Fix XS2A Security Hot Spots


a| * All fixes and updates from v.8.6

* Fix connector-examples for multilevel SCA


a|

a|

a|

a|

a|

a|

|14.01.2021| |8.7|9.6|

a|

a|

a| * Fix XS2A Security Hot Spots


a| * All fixes and updates from v.8.7

* Add new data type Entry Details

* Add link of type "card" to the Card Account Report

* Add optional attributes to the Transactions data type

* Add attribute debitAccounting to the card account details type

a|

a|

a|

a|

a|

a|

|27.01.2021| |8.8|9.7|

a|

a|

a| * Fix XS2A Security Hot Spots


a| * All fixes and updates from v.8.8

* Adjust counting Consent usage for several booking statuses

* Added a psuMessage into Get SCA Status Response

a|

a|

a|

a|

a|

a|

|11.02.2021| |8.9|9.8|

a|

a|

a| * Move to the latest version of Mapstruct

* Improve decoupled approach

* Bugfix: Update authorisation status after ATTEMPT_FAILURE

* Bugfix: expiration of old consnets for confirmation code cases

* Connector: Use get transaction list with pagination


a| * All fixes and updates from v.8.9


a| Signing Basket plugin for XS2A

a|

a|

a|

a|

a|

|25.02.2021| |8.10|9.9|

a|

a|

a|* Bugfix: SpiPeriodicPayment error on @Data annotation

* Bugfix: Validate format `dateFrom` and `dateTo` in getTransactionList

* Fix sonar alerts


a| * All fixes and updates from v.8.10


a| Signing Basket plugin for XS2A

a|

a|

a|

a|

a|

|10.03.2021| |8.11|9.10|

a|

a|

a|* Bugfix: Remove @NotNull from TppDomainValidator#validate

* Bugfix: Validate certificate roles for PIIS consent v2

* Bugfix: Faulty definition CmsPayment in REST API

* Fix sonar alerts


a| * All fixes and updates from v.8.10

* Update Ledgers to 4.7 in Connector

* Remove deprecated requestTrustedBeneficiaryFlag method in 9.10

a|

a|

a|

a|

a|

a|

|*For future development*| |10.x|11.x|

| | | | |Signing Basket plugin for XS2A

| | | | |Multiple consents plugin for XS2A

|====
