= Roadmap

Starting 1st of March 2020 XS2A-core Team is providing development within two branches:

*Stable branch 6.x*

Stable branch will contain bugfixing and possibly necessary changes to support mandatory endpoints defined by Berlin Group NextGenPSD2 Spec 1.3.6. Will be supported till 28.08.2020

*Development branch 7.x*

Development branch is oriented on implementation of new features and optional endpoints.
No backward compatibility with 6.x is guaranteed. Will be released as Stable version 8.x on 11.09.2020

[cols="3*.<"]
|===
|release date|version 6.x|version 7.x

|13.03.2020|6.0|7.0

a|

a|* New feature: Support header TPP-Brand-Logging-Information

* New feature: Retrieve psuMessage from SPI for Get Status Response

* New feature: In Get Payment Response the payment resource may contain the debtorName field

* New feature: Add new attributes to data types according to Specification v.1.3.6

* New feature: Add new message code 400 SCA_INVALID

* Bugfix: Validation for PIIS field cardNumber is missing

* Adjust Xs2a and SPI BalanceType objects with BG specification 1.3.6

a|* All fixes and updates from v.6.0

* Update to Java 11

|27.03.2020|6.1|7.1

a|

a|* Remove "owner_address_type" column from "ais_consent" table

* Bugfix: Validation for PIIS field cardNumber is missing

a|* All fixes and updates from v.6.1

* New feature: Funds Confirmation consent support in Profile

* New feature: Support yaml for Funds Confirmation consent

* New feature: Establish FundsConfirmationConsent

* New feature: Create Funds Confirmation consent validator

* New feature: Get FundsConfirmationConsent Status + object

* New feature: Revoke FundsConfirmationConsent

|10.04.2020|6.2|7.2

a|

a|* Remove deprecated PaymentAuthorisationType

* Remove deprecated PiisConsentTppAccessType 

* Drop deprecated tables for AIS and PIS authorisations

a|* All fixes and updates from v.6.2

* New feature: FundsConfirmationConsent in Embedded approach with multilevel SCA

* New feature: FundsConfirmationConsent in Decoupled approach with multilevel SCA

* New feature: Get Authorisation Sub-resource request for FundsConfirmationConsent

* New feature: Get SCA Status request for FundsConfirmationConsent 

|24.04.2020|6.3|7.3

a|

a|* Provide interfaces for CMS controllers

a|* All fixes and updates from v.6.3

* New feature: Create interfaces in cms-psu-api for FundsConfirmationConsent

* New feature: FundsConfirmationConsent in Redirect approach with multilevel SCA

|08.05.2020|6.4|7.4

a|

a|* Fix javadoc warnings

* Fix disabled test in EventReportRepositoryImplIT

* Remove unused AisConsentServiceBase#updateAspspAccountAccess

* Refactor method isConsentExpired in OneOffConsentExpirationService

a|* All fixes and updates from v.6.4

* New feature: Add a new optional header TPP-Rejection-NoFunds-Preferred

* Move authorisation-related methods out of Xs2aAisConsentService and Xs2aPisCommonPaymentService

|Further development| |

a|

a|

a|* New feature: Extension of possibility returning several camt.05x files in one zip file

* New feature: Create Resource Notification Push Service

* _Support of Signing Basket:_

- Create Signing Basket in CMS 

- Implement Establish Signing Basket request

- Implement Cancellation of Signing Baskets

- Support Signing Basket in Embedded approach with multilevel SCA

- Support Signing Basket in Decoupled approach with multilevel SCA

- Support Signing Basket in Redirect approach with multilevel SCA

- Implement Get Authorisation Sub-resources for Signing Baskets

- Create interfaces in cms-psu-api for Signing Basket

- Implement Get Signing Basket Status Request

- Implement Get Signing Basket Request 

- Implement Get SCA Status request for Signing Baskets

- Add calls to SPI for Signing Basket

|===