= Roadmap

Starting 1st of March 2020 XS2A-core Team is providing development within two branches:

*Stable branch 6.x*

Stable branch will contain bugfixing and possibly necessary changes to support mandatory endpoints defined by Berlin Group NextGenPSD2 Spec 1.3.6. Will be supported till 28.08.2020

*Development branch 7.x*

Development branch is oriented on implementation of new features and optional endpoints.
No backward compatibility with 6.x is guaranteed. Will be released as Stable version 8.x on 11.09.2020

[cols="5*.<"]
|===
|release date|version 6.x (Stable)|version 7.x (Development)|version 8.x (Stable)|version 9.x (Development)

|14.08.2020|6.8|7.8| | 

a|

a|* Add validator for accept-header

a|* All fixes and updates from v.6.8

* New feature: Revoke FundsConfirmationConsent

* New feature: FundsConfirmationConsent in Redirect approach with multilevel SCA

* New feature: FundsConfirmationConsent in Embedded approach with multilevel SCA

* New feature: Get Authorisation Sub-resource request for FundsConfirmationConsent

* New feature: Get SCA Status request for FundsConfirmationConsent 

* Adjust CoF request with consent created by TPP

a|

a|

|28.08.2020|6.9|7.9| |

a|

a|

a|* All fixes and updates from v.6.9

* New feature: FundsConfirmationConsent in Decoupled approach with multilevel SCA

* Fix all ToDos in code

a|

a|

|11.09.2020| | |8.0|9.0

a|

a|

a|

a|* Remove deprecated authorisation type AIS

a|* All fixes and updates from v.8.0

* New feature: Implement Read Card List

* New feature: Implement Read Card Details

* New feature: Implement Read Card Balances

* New feature: Implement Read Card Transaction List

* Adjust Create AIS consent request for Single card service

* Adjust Read AIS consent response links for Single card service

|25.09.2020| | |8.1|9.1

a|

a|

a|

a|

a|* All fixes and updates from v.8.1

* Create Signing Basket in CMS 

* Implement Establish Signing Basket request

* Implement Cancellation of Signing Baskets

|09.10.2020| | |8.2|9.2

a|

a|

a|

a|

a|* All fixes and updates from v.8.2

* Create interfaces in cms-psu-api for Signing Basket

|23.10.2020| | |8.3|9.3

a|

a|

a|

a|

a|* All fixes and updates from v.8.3

* Support Signing Basket in Redirect approach with multilevel SCA

|06.11.2020| | |8.4|9.4

a|

a|

a|

a|

a|* All fixes and updates from v.8.4

* Support Signing Basket in Embedded approach with multilevel SCA

|20.11.2020| | |8.5|9.5

a|

a|

a|

a|

a|* All fixes and updates from v.8.5

* Implement Get Authorisation Sub-resources for Signing Baskets

* Implement Get Signing Basket Status Request

* Implement Get Signing Basket Request 

* Implement Get SCA Status request for Signing Baskets

|04.12.2020| | |8.6|9.6

a|

a|

a|

a|

a|* All fixes and updates from v.8.6

* Support Signing Basket in Decoupled approach with multilevel SCA

* Add calls to SPI for Signing Basket

|Further development| | | |

a|

a|

a|

a|

a|* New feature: Add a new optional header TPP-Rejection-NoFunds-Preferred

* New feature: Extension of possibility returning several camt.05x files in one zip file

* New feature: Create Resource Notification Push Service

* Support URL-encoded QWAC certificate in header

* Extend the event table with all types of Update PSU Data requests

|===