= Roadmap

Starting 1st of September 2019 XS2A Team is providing development within two branches:

*Stable branch 4.x*

Stable branch will contain bugfixing and possibly necessary changes to support mandatory endpoints defined by Berlin Group NextGenPSD2 Spec 1.3.5. Will be supported till 01.03.2020

*Development branch 5.x*

Development branch is oriented on implementation of new features and optional endpoints.
No backward compatibility with 4.x is guaranteed. Will be released as Stable version 6.x on 13.03.2020

[cols="5*.<"]
|===
|release date|version 4.x|version 5.x|version 6.x|version 7.x

|28.02.2020|4.11|5.11| |

a|

a|* Update expiration rule for not authorised payment\consent

* Rename expireDate property in AisConsentSha to validUntil and migrate existings AIS checksums

* Delete specific constructor in SpiAccountConsent

a|* All fixes and updates from v.4.11

* Adjust consent model in CMS

* Create new SPI method for handling consent wrapper

* Migrate data of Funds Confirmation consent v1

* Add not null constraint for "valid_until" field in "ais_consent" table

* Bugfix: Wrong response for consent creation with additionalInformation ownerName

a|

a|

|13.03.2020| | |6.0|7.0

a|

a|

a|

a|* New feature: Support header TPP-Brand-Logging-Information

* New feature: Retrieve psuMessage from SPI for Get Status Response

* New feature: In Get Payment Response the payment resource may contain the debtorName field

* New feature: Add new attributes to data types according to Specification v.1.3.6

* New feature: Add new message code 400 SCA_INVALID

a|* All fixes and updates from v.6.0

* Update to Java 11

* Complete common payment migration in CMS database

|27.03.2020| | |6.1|7.1

a|

a|

a|

a|* Remove "owner_address_type" column from "ais_consent" table

a|* All fixes and updates from v.6.1

* New feature: Funds Confirmation consent support in Profile

* New feature: Support yaml for Funds Confirmation consent

* New feature: Establish FundsConfirmationConsent

* New feature: Create Funds Confirmation consent validator

* New feature: Get FundsConfirmationConsent Status + object

* New feature: Revoke FundsConfirmationConsent

|10.04.2020| | |6.2|7.2

a|

a|

a|

a|* Remove deprecated PaymentAuthorisationType

* Drop deprecated tables for AIS and PIS authorisations

a|* All fixes and updates from v.6.2

* New feature: FundsConfirmationConsent in Embedded approach with multilevel SCA

* New feature: FundsConfirmationConsent in Decoupled approach with multilevel SCA

* New feature: Get Authorisation Sub-resource request for FundsConfirmationConsent

* New feature: Get SCA Status request for FundsConfirmationConsent 

|24.04.2020| | |6.3|7.3

a|

a|

a|

a|* Provide interfaces for CMS controllers

a|* All fixes and updates from v.6.3

* New feature: Create interfaces in cms-psu-api for FundsConfirmationConsent

* New feature: FundsConfirmationConsent in Redirect approach with multilevel SCA

|08.05.2020| | |6.4|7.4

a|

a|

a|

a|* Fix javadoc warnings

* Fix disabled test in EventReportRepositoryImplIT

* Remove unused AisConsentServiceBase#updateAspspAccountAccess

* Refactor method isConsentExpired in OneOffConsentExpirationService

a|* All fixes and updates from v.6.4

* New feature: Add a new optional header TPP-Rejection-NoFunds-Preferred

* Move authorisation-related methods out of Xs2aAisConsentService and Xs2aPisCommonPaymentService

|Further development| | | |

a|

a|

a|

a|

a|* New feature: Extension of possibility returning several camt.05x files in one zip file

* New feature: Create Resource Notification Push Service

* _Support of Signing Basket:_

- Create Signing Basket in CMS 

- Implement Establish Signing Basket request

- Implement Cancellation of Signing Baskets

- Support Signing Basket in Embedded approach with multilevel SCA

- Support Signing Basket in Decoupled approach with multilevel SCA

- Support Signing Basket in Redirect approach with multilevel SCA

- Implement Get Authorisation Sub-resources for Signing Baskets

- Create interfaces in cms-psu-api for Signing Basket

- Implement Get Signing Basket Status Request

- Implement Get Signing Basket Request 

- Implement Get SCA Status request for Signing Baskets

- Add calls to SPI for Signing Basket

|===