{{ if and .Values.cmsPortal.enabled .Values.cmsPortal.route.enabled }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
{{- with .Values.cmsPortal.route.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  name: {{ template "psd2.fullname" . }}-cmsportal
  labels:
{{ include "psd2.labels" . | indent 4 }}
    app.kubernetes.io/component: cmsPortal
    app: aspsp-mock
spec:
  host: {{ tpl (required "cmsPortal.route.host must be defined" .Values.cmsPortal.route.host) . | quote }}
  port:
    targetPort: http
{{- with .Values.cmsPortal.route.tls }}
  tls:
{{ toYaml . | indent 4 }}
{{- end }}
  to:
    kind: Service
    name: {{ template "psd2.fullname" . }}-cmsportal
    weight: 100
    wildcardPolicy: None
{{- end }}
