/**
 * XS2A REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: fpo@adorsys.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccountReference } from './accountReference';
import { Amount } from './amount';
import { PurposeCode } from './purposeCode';
import { TheBankTransactionCode } from './theBankTransactionCode';


/**
 * TransactionsCreditorResponse information
 */
export interface TransactionsCreditorResponse {
    /**
     * Amount
     */
    amount: Amount;
    /**
     * Bank transaction code as used by the ASPSP in ISO20022 related formats.
     */
    bankTransactionCodeCode?: TheBankTransactionCode;
    /**
     * Booking Date
     */
    bookingDate?: string;
    /**
     * Creditor account
     */
    creditorAccount?: AccountReference;
    /**
     * Identification of Creditors, e.g. a SEPA Creditor ID
     */
    creditorId?: string;
    /**
     * Name of the Creditor if a debited transaction
     */
    creditorName?: string;
    /**
     * Debtor account
     */
    debtorAccount?: AccountReference;
    /**
     * Name of the debtor if a “Credited” transaction
     */
    debtorName?: string;
    /**
     * End to end id
     */
    endToEndId?: string;
    /**
     * Identification of Mandates, e.g. a SEPA Mandate ID
     */
    mandateId?: string;
    /**
     * Purpose code
     */
    purposeCode?: PurposeCode;
    /**
     * Remittance information structured;
     */
    remittanceInformationStructured?: string;
    /**
     * Remittance information unstructured
     */
    remittanceInformationUnstructured?: string;
    /**
     * Can be used as access-ID in the API, where more details on an transaction is offered.
     */
    transactionId?: string;
    /**
     * Name of the last creditor
     */
    ultimateCreditor?: string;
    /**
     * Name of the last debtor
     */
    ultimateDebtor?: string;
    /**
     * Value Date
     */
    valueDate?: string;
}
