/**
 * XS2A REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: fpo@adorsys.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccountReference } from './accountReference';


/**
 * Account access
 */
export interface AccountAccess {
    /**
     * detailed account information
     */
    accounts?: Array<AccountReference>;
    /**
     * only the value 'allAccounts' or 'allAccountsWithBalances' is admitted
     */
    allPsd2?: AccountAccess.AllPsd2Enum;
    /**
     * only the value 'allAccounts' is admitted
     */
    availableAccounts?: AccountAccess.AvailableAccountsEnum;
    /**
     * balances of the addressed accounts
     */
    balances?: Array<AccountReference>;
    /**
     * transactions of the addressed accounts
     */
    transactions?: Array<AccountReference>;
}
export namespace AccountAccess {
    export type AllPsd2Enum = 'allAccounts';
    export const AllPsd2Enum = {
        Accounts: 'allAccounts' as AllPsd2Enum
    }
    export type AvailableAccountsEnum = 'allAccounts';
    export const AvailableAccountsEnum = {
        Accounts: 'allAccounts' as AvailableAccountsEnum
    }
}
