@startuml
skinparam componentStyle uml2

component "TPP" as TPP
component "Certification\nAuthority" as CA
interface XS2A #white

TPP .> XS2A : access\nASPSP
CA <.. TPP

component "Gateway" as GW #moccasin

component "ASPSP Systems \n" #moccasin {
    component "ASPSP" as ASPSP #lightyellow
    component "ASPSP Auth" as auth #lightyellow

    auth ..> ASPSP : process\nrequest
}

component "PSD2 XS2A Service \n" {
    component "ASPSP\nProfile" as profile #white
    component "XS2A Service" as xs2aimpl #white
    component "CMS" as cms #white
    interface "SPI-API" as spi #white
    component "ASPSP-Connector" as connector #lightblue
    interface "XS2A" as XS2AI #white
    interface "CMS PSU API" as cms_psu
    interface "CMS ASPSP API" as cms_aspsp

    CA <.. GW : validate\nTPP

    profile <.. xs2aimpl : access\nprofile
    profile <.. cms : access\nprofile

    XS2A - GW
    GW .> XS2AI : proxy\nTPP Request
    XS2AI - xs2aimpl
    xs2aimpl -- spi
    spi <|--connector
    xs2aimpl .> cms : manage\nconsent
    cms - cms_psu
    cms -- cms_aspsp


    connector .> ASPSP : process\nrequest

    cms_psu <. auth : update status
    cms_aspsp <. ASPSP : access\nconsents
}


@enduml

