/*
 * Copyright 2018-2022 adorsys GmbH & Co KG
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or (at
 * your option) any later version. This program is distributed in the hope that
 * it will be useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://www.gnu.org/licenses/.
 *
 * This project is also available under a separate commercial license. You can
 * contact us at psd2@adorsys.com.
 */

package de.adorsys.psd2.event.core.model;

public enum EventType {
    /* Signing basket */
    CREATE_SIGNING_BASKET_REQUEST_RECEIVED,
    DELETE_SIGNING_BASKET_REQUEST_RECEIVED,
    GET_SIGNING_BASKET_REQUEST_RECEIVED,
    GET_SIGNING_BASKET_STATUS_REQUEST_RECEIVED,
    GET_SIGNING_BASKET_SCA_STATUS_REQUEST_RECEIVED,
    START_SIGNING_BASKET_AUTHORISATION_REQUEST_RECEIVED,
    UPDATE_SB_PSU_DATA_IDENTIFICATION_REQUEST_RECEIVED,
    UPDATE_SB_PSU_DATA_AUTHENTICATION_REQUEST_RECEIVED,
    UPDATE_SB_PSU_DATA_SELECT_AUTHENTICATION_METHOD_REQUEST_RECEIVED,
    UPDATE_SB_PSU_DATA_TAN_REQUEST_RECEIVED,
    UPDATE_SB_PSU_DATA_CONFIRMATION_CODE_REQUEST_RECEIVED,
    GET_SIGNING_BASKET_AUTHORISATION_REQUEST_RECEIVED,
    /* PIIS Funds Confirmation */
    CREATE_PIIS_CONSENT_REQUEST_RECEIVED,
    DELETE_PIIS_CONSENT_REQUEST_RECEIVED,
    GET_PIIS_CONSENT_REQUEST_RECEIVED,
    FUNDS_CONFIRMATION_REQUEST_RECEIVED,
    @Deprecated
    UPDATE_PIIS_CONSENT_PSU_DATA_REQUEST_RECEIVED,
    UPDATE_PIIS_CONSENT_PSU_DATA_IDENTIFICATION_REQUEST_RECEIVED,
    UPDATE_PIIS_CONSENT_PSU_DATA_AUTHENTICATION_REQUEST_RECEIVED,
    UPDATE_PIIS_CONSENT_PSU_DATA_SELECT_AUTHENTICATION_METHOD_REQUEST_RECEIVED,
    UPDATE_PIIS_CONSENT_PSU_DATA_TAN_REQUEST_RECEIVED,
    UPDATE_PIIS_CONSENT_PSU_DATA_CONFIRMATION_CODE_REQUEST_RECEIVED,
    GET_PIIS_CONSENT_STATUS_REQUEST_RECEIVED,
    /* PIIS Consent Authorisation */
    START_PIIS_CONSENT_AUTHORISATION_REQUEST_RECEIVED,
    GET_PIIS_CONSENT_AUTHORISATION_REQUEST_RECEIVED,
    GET_PIIS_CONSENT_SCA_STATUS_REQUEST_RECEIVED,
    /* AIS Consent */
    CREATE_AIS_CONSENT_REQUEST_RECEIVED,
    DELETE_AIS_CONSENT_REQUEST_RECEIVED,
    GET_AIS_CONSENT_REQUEST_RECEIVED,
    GET_AIS_CONSENT_STATUS_REQUEST_RECEIVED,
    /* AIS Consent Authorisation */
    GET_CONSENT_AUTHORISATION_REQUEST_RECEIVED,
    GET_CONSENT_SCA_STATUS_REQUEST_RECEIVED,
    START_AIS_CONSENT_AUTHORISATION_REQUEST_RECEIVED,
    @Deprecated
    UPDATE_AIS_CONSENT_PSU_DATA_REQUEST_RECEIVED,
    UPDATE_AIS_CONSENT_PSU_DATA_IDENTIFICATION_REQUEST_RECEIVED,
    UPDATE_AIS_CONSENT_PSU_DATA_AUTHENTICATION_REQUEST_RECEIVED,
    UPDATE_AIS_CONSENT_PSU_DATA_SELECT_AUTHENTICATION_METHOD_REQUEST_RECEIVED,
    UPDATE_AIS_CONSENT_PSU_DATA_TAN_REQUEST_RECEIVED,
    UPDATE_AIS_CONSENT_PSU_DATA_CONFIRMATION_CODE_REQUEST_RECEIVED,
    /* AIS Account information */
    READ_ACCOUNT_DETAILS_REQUEST_RECEIVED,
    READ_ACCOUNT_LIST_REQUEST_RECEIVED,
    READ_BALANCE_REQUEST_RECEIVED,
    READ_TRANSACTION_DETAILS_REQUEST_RECEIVED,
    READ_TRANSACTION_LIST_REQUEST_RECEIVED,
    DOWNLOAD_TRANSACTION_LIST_REQUEST_RECEIVED,
    READ_TRUSTED_BENEFICIARIES_LIST_REQUEST_RECEIVED,
    /* AIS Card account information */
    READ_CARD_ACCOUNT_LIST_REQUEST_RECEIVED,
    READ_CARD_ACCOUNT_DETAILS_REQUEST_RECEIVED,
    READ_CARD_BALANCE_REQUEST_RECEIVED,
    READ_CARD_TRANSACTION_LIST_REQUEST_RECEIVED,
    /* PIS Payment */
    PAYMENT_INITIATION_REQUEST_RECEIVED,
    GET_PAYMENT_REQUEST_RECEIVED,
    GET_TRANSACTION_STATUS_REQUEST_RECEIVED,
    PAYMENT_CANCELLATION_REQUEST_RECEIVED,
    /* PIS Payment Authorisation */
    START_PAYMENT_AUTHORISATION_REQUEST_RECEIVED,
    GET_PAYMENT_CANCELLATION_AUTHORISATION_REQUEST_RECEIVED,
    @Deprecated
    UPDATE_PAYMENT_CANCELLATION_PSU_DATA_REQUEST_RECEIVED,
    UPDATE_PAYMENT_CANCELLATION_PSU_DATA_IDENTIFICATION_REQUEST_RECEIVED,
    UPDATE_PAYMENT_CANCELLATION_PSU_DATA_AUTHENTICATION_REQUEST_RECEIVED,
    UPDATE_PAYMENT_CANCELLATION_PSU_DATA_SELECT_AUTHENTICATION_METHOD_REQUEST_RECEIVED,
    UPDATE_PAYMENT_CANCELLATION_PSU_DATA_TAN_REQUEST_RECEIVED,
    UPDATE_PAYMENT_CANCELLATION_PSU_DATA_CONFIRMATION_CODE_REQUEST_RECEIVED,
    @Deprecated
    UPDATE_PAYMENT_AUTHORISATION_PSU_DATA_REQUEST_RECEIVED,
    UPDATE_PAYMENT_AUTHORISATION_PSU_DATA_IDENTIFICATION_REQUEST_RECEIVED,
    UPDATE_PAYMENT_AUTHORISATION_PSU_DATA_AUTHENTICATION_REQUEST_RECEIVED,
    UPDATE_PAYMENT_AUTHORISATION_PSU_DATA_SELECT_AUTHENTICATION_METHOD_REQUEST_RECEIVED,
    UPDATE_PAYMENT_AUTHORISATION_PSU_DATA_TAN_REQUEST_RECEIVED,
    UPDATE_PAYMENT_AUTHORISATION_PSU_DATA_CONFIRMATION_CODE_REQUEST_RECEIVED,
    START_PAYMENT_CANCELLATION_AUTHORISATION_REQUEST_RECEIVED,
    GET_PAYMENT_AUTHORISATION_REQUEST_RECEIVED,
    GET_PAYMENT_SCA_STATUS_REQUEST_RECEIVED,
    GET_PAYMENT_CANCELLATION_SCA_STATUS_REQUEST_RECEIVED,
}
