/**
 * XS2A SPI MOCK API
 * Mock server to simulate ASPSP
 *
 * OpenAPI spec version: 1.0
 * Contact: dgo@adorsys.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SpiAmount } from './spiAmount';


export interface SpiAccountBalance {
    lastChangeDateTime?: Date;
    lastCommittedTransaction?: string;
    referenceDate?: string;
    spiBalanceAmount?: SpiAmount;
    spiBalanceType?: SpiAccountBalance.SpiBalanceTypeEnum;
}
export namespace SpiAccountBalance {
    export type SpiBalanceTypeEnum = 'CLOSING_BOOKED' | 'EXPECTED' | 'AUTHORISED' | 'OPENING_BOOKED' | 'INTERIM_AVAILABLE' | 'FORWARD_AVAILABLE';
    export const SpiBalanceTypeEnum = {
        CLOSINGBOOKED: 'CLOSING_BOOKED' as SpiBalanceTypeEnum,
        EXPECTED: 'EXPECTED' as SpiBalanceTypeEnum,
        AUTHORISED: 'AUTHORISED' as SpiBalanceTypeEnum,
        OPENINGBOOKED: 'OPENING_BOOKED' as SpiBalanceTypeEnum,
        INTERIMAVAILABLE: 'INTERIM_AVAILABLE' as SpiBalanceTypeEnum,
        FORWARDAVAILABLE: 'FORWARD_AVAILABLE' as SpiBalanceTypeEnum
    }
}
