/*
 * Copyright 2018-2022 adorsys GmbH & Co KG
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or (at
 * your option) any later version. This program is distributed in the hope that
 * it will be useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://www.gnu.org/licenses/.
 *
 * This project is also available under a separate commercial license. You can
 * contact us at psd2@adorsys.com.
 */

package de.adorsys.psd2.xs2a.domain;

import de.adorsys.psd2.xs2a.core.psu.PsuIdData;
import lombok.Value;

import java.util.Map;
import java.util.UUID;

/**
 * Contains general information about the incoming request.
 */
@Value
public class RequestData {
    /**
     * Returns the part of the request's URL after the server name and port number.
     * Example: '/v1/consents'
     */
    private String uri;

    /**
     * Unique ID of the request, generated by the XS2A itself.
     */
    private UUID internalRequestId;

    /**
     * Unique ID of the request, which was received as X-Request-ID in the header.
     */
    private UUID requestId;

    /**
     * IP address, from which the request was sent.
     */
    private String ip;

    /**
     * Headers used in the request.
     */
    private Map<String, String> headers;

    /**
     * PSU data
     */
    private PsuIdData psuIdData;
}
