/**
 * XS2A SPI MOCK API
 * Mock server to simulate ASPSP
 *
 * OpenAPI spec version: 1.0
 * Contact: dgo@adorsys.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SpiAmount {
    currency?: string;
    content?: number;
}
