/**
 * XS2A SPI MOCK API
 * Mock server to simulate ASPSP
 *
 * OpenAPI spec version: 1.0
 * Contact: dgo@adorsys.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SpiAccountBalance } from './spiAccountBalance';


export interface SpiAccountDetails {
    id?: string;
    iban?: string;
    bban?: string;
    pan?: string;
    maskedPan?: string;
    msisdn?: string;
    currency?: string;
    name?: string;
    accountType?: string;
    cashSpiAccountType?: SpiAccountDetails.CashSpiAccountTypeEnum;
    bic?: string;
    balances?: Array<SpiAccountBalance>;
}
export namespace SpiAccountDetails {
    export type CashSpiAccountTypeEnum = 'CURRENT_ACCOUNT';
    export const CashSpiAccountTypeEnum = {
        ACCOUNT: 'CURRENT_ACCOUNT' as CashSpiAccountTypeEnum
    }
}
