/**
 * XS2A SPI MOCK API
 * Mock server to simulate ASPSP
 *
 * OpenAPI spec version: 1.0
 * Contact: dgo@adorsys.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SpiAccountReference } from './spiAccountReference';
import { SpiAmount } from './spiAmount';


export interface SpiTransaction {
    pendingTransaction?: boolean;
    transactionId?: string;
    endToEndId?: string;
    mandateId?: string;
    creditorId?: string;
    bookingDate?: string;
    valueDate?: string;
    spiAmount?: SpiAmount;
    creditorName?: string;
    creditorAccount?: SpiAccountReference;
    ultimateCreditor?: string;
    debtorName?: string;
    debtorAccount?: SpiAccountReference;
    ultimateDebtor?: string;
    remittanceInformationUnstructured?: string;
    remittanceInformationStructured?: string;
    purposeCode?: string;
    bankTransactionCodeCode?: string;
}
