@startuml

node "XS2A-Service" as node_xs2a {
    artifact XS2AService {
        component "xs2a-impl.jar" as xs2a_impl
        component "consent-xs2a-client.jar" as cms_client
        component "spi-impl.jar" as spi_impl #lightblue
        component "aspsp-profile-remote.jar" as profile_remote

        component "Main XS2A Service Application" as main #lightblue

        xs2a_impl .> cms_client
        xs2a_impl ..> spi_impl
        profile_remote <.. xs2a_impl

        spi_impl -[hidden] main
    }
    file "application.yml" as config
    file "swagger.json" as swagger
    file "logback.xml" as logback

    main -- config
    main -- swagger
    main -- logback
}

artifact "ASPSPProfile"

ASPSPProfile <.. profile_remote

artifact "Consent-management-system" as CMS

cms_client .> CMS

@enduml
