@startuml

actor TPP

node "API Gateway" as node_gw {
    interface "Load balancer" as lb
}

TPP ..> lb: HTTP/TLS


node "XS2A-Service, instance N" {
    artifact XS2AService as xs2a_1
    artifact ASPSPProfile as aspsp_1
    artifact CMS as cms_1

lb ..> xs2a_1 : "HTTP         \n(XS2A API)      "


aspsp_1 <... cms_1 : "Java call"
aspsp_1 <... xs2a_1: "Java call"
xs2a_1 .> cms_1 : "Java call"
}

node "XS2A-Service, instance 0" {
    artifact XS2AService as xs2a_0
    artifact "ASPSPProfile" as aspsp_0
    artifact "CMS" as cms_0

lb ...> xs2a_0 : "HTTP       \n(XS2A API)      "

aspsp_0 <... cms_0 : "Java call"
aspsp_0 <... xs2a_0: "Java call"
xs2a_0 .> cms_0 : "Java call"
}

node Database {
    database ConsentDB
}

cms_0 ..> ConsentDB: JDBC
cms_1 ..> ConsentDB: JDBC


@enduml
