@startuml

actor TPP

node "API Gateway" as node_gw {
    interface "Load balancer" as lb
}

TPP .> lb: "HTTP/TLS                "

node "ASPSP profile" {
    artifact ASPSPProfile
}

node "XS2A-Service, \n instance 0" as node_xs2a {
    artifact XS2AService as xs2a_0

lb .> xs2a_0 : "HTTP         \n(XS2A API)      "
xs2a_0 ..> ASPSPProfile: "HTTP/REST"
}

node "XS2A-Service, \n instance N" {
    artifact XS2AService as xs2a_1

lb ..> xs2a_1 : "HTTP       \n(XS2A API)      "
xs2a_1 ..> ASPSPProfile: "HTTP/REST"
}

node "Consent \nManagement \nSystem" {
    artifact CMS as cms
}

node Database {
    database ConsentDB
}

xs2a_0 .> cms : "HTTP/REST"
xs2a_1 .> cms : "HTTP/REST"
ASPSPProfile <.... cms : "HTTP/REST"

cms .> ConsentDB: "           JDBC      "

@enduml
