@startuml

title Event workflow using HTTP

cloud "TPP"{
}

package "XS2A" {
  [event-service-rest-client]
}

package "CMS" {
  [event-service-persist-api]
  [event-service-xs2a-api]
}

database "Database"
queue "Queue"
folder "File system" AS FS

TPP --> XS2A

[event-service-rest-client] ..> [event-service-xs2a-api] : HTTP request
[event-service-xs2a-api] --> [event-service-persist-api]

[event-service-persist-api] --> Database
[event-service-persist-api] --> Queue
[event-service-persist-api] --> FS

@enduml
