/*
 * Copyright 2018-2018 adorsys GmbH & Co KG
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package de.adorsys.aspsp.xs2a.domain.pis;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import de.adorsys.psd2.xs2a.spi.domain.consent.AspspConsentData;
import io.swagger.annotations.ApiModel;
import lombok.Data;
import lombok.EqualsAndHashCode;

// TODO Create separate response classes for each payment type https://git.adorsys.de/adorsys/xs2a/aspsp-xs2a/issues/425

/**
 * @deprecated since 1.8. Will be removed in 1.10
 * @see PaymentInitiationResponse
 */
@Deprecated
@Data
@EqualsAndHashCode(callSuper = true)
@ApiModel(description = "Response Body generated by the Payment Service")
@JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
public class PaymentInitialisationResponse extends PaymentInitiationResponse {
    @JsonIgnore
    private String paymentType;

    @JsonIgnore //TODO remote it from here https://git.adorsys.de/adorsys/xs2a/aspsp-xs2a/issues/332
    private AspspConsentData aspspConsentData;
}

