{{ if .Values.xs2a.enabled }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
{{- with .Values.xs2a.route.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  name: {{ template "psd2.fullname" . }}-xs2a
  labels:
{{ include "psd2.labels" . | indent 4 }}
    app.kubernetes.io/component: xs2a
spec:
  host: {{ tpl (required "xs2a.route.host must be defined" .Values.xs2a.route.host) . | quote }}
  port:
    targetPort: http
{{- with .Values.xs2a.route.tls }}
  tls:
{{ toYaml . | indent 4 }}
{{- end }}
  to:
    kind: Service
    name: {{ template "psd2.fullname" . }}-xs2a
    weight: 100
    wildcardPolicy: None
{{- end }}
