// toc-title definition MUST follow document title without blank line!
== Funds Confirmation Service
:toc-title:
:imagesdir: ../usecases/diagrams
:toc: left

toc::[]

The overall confirmation of funds service is separated in two phases:

* Establish PIIS consent (Optional);

* Perform the actual Confirmation of Funds request through XS2A.

The first part is not mandated to be offered by the XS2A interface, since this could also be an online banking function or even a paper based consent process.

* Parameter *"piisConsentSupported"* in the ASPSP-Profile defines which model of PIIS Consent ASPSP supports:

** *NOT_SUPPORTED* (No need to create PIIS consent in CMS for availability of funds check,
Confirmation of Funds request is being passed to SPI level as is (no consent validation is performed by XS2A) and ASPSP is responsible for proper handling of such a request);

** *TPP_CONSENT_SUPPORTED* (Establish PIIS Consent through XS2A interface);

** *ASPSP_CONSENT_SUPPORTED* (ASPSP creates PIIS consent in CMS and Confirmation of Funds request is validated according to this consent);

* If TPP has no Valid PIIS Consent and tries to request Funds Confirmation, then response contains *HTTP code  400 "NO_PIIS_ACTIVATION"*;
* When parameter *"piisConsentSupported"* in the ASPSP-Profile set to *ASPSP_CONSENT_SUPPORTED* and PIIS Consent is stored in CMS without TPP-Authorisation-Number,
this PIIS consent can be used by any TPP. If TPP-Authorisation-Number is set in consent - PIIS consent is for particular TPP;
* Funds Confirmation should be requested by the same TPP which is written in Consent. In case when validation is *unsuccessful*, XS2A sends the response with *HTTP code 400 CONSENT_UNKNOWN*.
* If Establish PIIS Consent through XS2A interface is not supported by ASPSP (parameter *"piisConsentSupported"* = *NOT_SUPPORTED* or *ASPSP_CONSENT_SUPPORTED*), then XS2A sends the response with *HTTP 405 SERVICE_INVALID*.

=== PIIS Consent created by ASPSP
* While creating PIIS consent by ASPSP, in case of existing old valid consent for TPP, one PSU and one account (Mandatory)-its consent status becomes *"RevokedByPSU"* as soon as new one for the same TPP, the same PSU and the same account is created with status Valid.

=== PIIS Consent created by TPP
TPP is able to establish PIIS consent through XS2A by sending request `POST /v2/consents/confirmation-of-funds`. Create funds confirmation consent request is validated according to specification.
There is no information about expiration of Funds Confirmation Consent created by TPP, so it will stay *VALID* until TPP or ASPSP revokes it.

Also TPP can receive content of previously created PIIS consent (`GET v2/consents/confirmation-of-funds/{consent_id}`)
and retrieve PIIS consent status (`GET v2/consents/confirmation-of-funds/{consent_id}/status`).
