// toc-title definition MUST follow document title without blank line!
= Strong customer authentication
:toc-title:
:imagesdir: usecases/diagrams
:toc: left

// horizontal line
***

toc::[]

Following transactions require strong customer authentication (SCA) of the PSU at the XS2A interface as part of the transaction:

* Payment initiation transactions.
* Cancellation initiation transactions (depending on the regulations for this kind of
  transactions at the user interfaces offered by the ASPSP to the PSU directly).
* Establish account information consent transactions.

== SCA Approaches
XS2A Interface supports multiple SCA approaches. https://github.com/adorsys/xs2a/tree/develop/aspsp-profile[ASPSP-Profile] may contain a list of approaches (in order of priority - first one with the highest priority).
Choice of SCA approach also depends on header parameter in initial request - TPP-Redirect-Preferred.
If TPP-Redirect-Preferred is true and ASPSP supports REDIRECT approach, then REDIRECT approach is used. Otherwise first approach in ASPSP-profile is used.

.A list of SCA approaches in ASPSP-Profile
|===
|Option |Meaning |Value

|scaApproaches
|List of SCA Approaches supported by ASPSP ordered by priority
|REDIRECT, EMBEDDED, DECOUPLED
|===

=== SCA using the redirect approach
For the redirect approach the individual steps of the SCA are not executed at the XS2A interface, but directly between the PSU and the ASPSP. In this case, the PSU is redirected to a web interface of the ASPSP for authentication.
Once the PSU has been redirected to the ASPSP (app or web interface) the SCA of the PSU is executed step by step and directly between the ASPSP and the PSU. After completion of the SCA the PSU is redirected back to the TPP.

=== SCA using the decoupled approach
The transaction flow of the decoupled approach to SCA is similar to that of the redirect approach. The difference is that the ASPSP asks the PSU to authenticate e.g. by sending a push notification with payment transaction details to a dedicated mobile app or via any other application or device which is independent of the online banking frontend.
The first factor of authorisation process is executed on XS2A side and the second one through the bank application

=== SCA using the embedded approach
When applying the embedded approach the SCA of the PSU is executed entirely as part of the transaction at the XS2A interface.

== Explicit/Implicit start of authorisation
Explicit start of authorisation is supported in case of Multilevel SCA and in case of Signing Basket, otherwise there is implicit start of authorisation.

== Authorisation (SCA) Statuses
Statuses which are defined finalised:

* Finalised (The SCA routine has been finalised successfully)
* Failed(The SCA routine failed)
* Exempted (SCA was exempted for the related transaction, the related authorisation is successful)

After setting finalised status for Authorisation status isn't allowed to be changed in CMS any more.
